ALTER TABLE recordings
    ADD COLUMN IF NOT EXISTS media_kind TEXT NOT NULL DEFAULT 'video',
    ADD COLUMN IF NOT EXISTS source TEXT NOT NULL DEFAULT 'obs',
    ADD COLUMN IF NOT EXISTS metadata JSONB NOT NULL DEFAULT '{}'::jsonb;
