#!/usr/bin/env node
// Writes one story file per component. Every component gets a Default story, a story per
// documented variant and state, and an Anatomy story that shows it beside the reference
// measurements it was built from. `--check` fails when a committed story file is out of date.
//
// The sample content lives in stories/samples.json. It is deliberately real — Hungarian strings
// where the product is Hungarian, long titles where truncation matters — because a catalog full
// of "Label" proves nothing about how the design behaves.
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { packageDir } from './tokens-lib.mjs';

const samples = JSON.parse(readFileSync(join(packageDir, 'stories/samples.json'), 'utf8'));

/** Where each exported component lives, read from the entry point rather than guessed. */
const LOCATION = new Map(
  [...readFileSync(join(packageDir, 'src/index.ts'), 'utf8').matchAll(
    /export \{ default as (\w+) \} from '\.\/(\w+)\//g,
  )].map((m) => [m[1], m[2]]),
);
const GROUP = { primitives: 'Primitives', patterns: 'Patterns', a11y: 'Accessibility' };

/** Story args as source, so a snippet or a handler can appear beside a plain value. */
function literal(value, indent = '    ') {
  if (value === null || value === undefined) return 'undefined';
  if (typeof value === 'string') {
    return value.startsWith('!') ? value.slice(1) : JSON.stringify(value);
  }
  if (typeof value !== 'object') return JSON.stringify(value);
  if (Array.isArray(value)) {
    if (value.length === 0) return '[]';
    return `[\n${value.map((v) => `${indent}  ${literal(v, indent + '  ')},`).join('\n')}\n${indent}]`;
  }
  const entries = Object.entries(value);
  if (entries.length === 0) return '{}';
  return `{\n${entries
    .map(([k, v]) => `${indent}  ${/^[a-z][\w]*$/i.test(k) ? k : JSON.stringify(k)}: ${literal(v, indent + '  ')},`)
    .join('\n')}\n${indent}}`;
}

const argsBlock = (args, indent = '  ') =>
  Object.entries(args)
    .map(([k, v]) => `${indent}  ${/^[a-z][\w]*$/i.test(k) ? k : JSON.stringify(k)}: ${literal(v, indent + '  ')},`)
    .join('\n');

function render(name, sample) {
  const path = LOCATION.get(name);
  const group = GROUP[path];
  const body = JSON.stringify(sample);
  const lines = [
    `// GENERATED by scripts/build-stories.mjs from stories/samples.json. Edit that, not this.`,
    `import type { Meta, StoryObj } from '@storybook/svelte-vite';`,
    `import ${name} from '../src/${path}/${name}.svelte';`,
    `import Anatomy from './support/Anatomy.svelte';`,
    ...(body.includes('!s(') ? [`import { s } from './support/snippet.js';`] : []),
    ``,
    `const meta = {`,
    `  title: '${group}/${name}',`,
    `  component: ${name},`,
    `  tags: ['autodocs'],`,
    `  parameters: {`,
    `    docs: { description: { component: 'Specification: docs/${name}.md' } },`,
    `  },`,
    `} satisfies Meta<${name}>;`,
    ``,
    `export default meta;`,
    `type Story = StoryObj<typeof meta>;`,
    ``,
  ];

  for (const [storyName, story] of Object.entries(sample.stories)) {
    if (story.$comment) lines.push(`/** ${story.$comment} */`);
    const args = { ...sample.args, ...story };
    delete args.$comment;
    lines.push(`export const ${storyName}: Story = {`, `  args: {`, argsBlock(args), `  },`, `};`, ``);
  }

  // Every component ends with its measurements, so drift is visible where the work happens.
  lines.push(
    `/** The component beside the reference declarations its values were taken from. */`,
    `export const Anatomy_: Story = {`,
    `  name: 'Anatomy & reference',`,
    `  render: () => ({ Component: Anatomy, props: { component: '${name}' } }),`,
    `};`,
    ``,
  );

  return lines.join('\n');
}

const stale = [];
let written = 0;

for (const [name, sample] of Object.entries(samples)) {
  if (name.startsWith('$')) continue;
  const source = render(name, sample);
  const out = join(packageDir, `stories/${name}.stories.ts`);
  if (process.argv.includes('--check')) {
    let current = '';
    try {
      current = readFileSync(out, 'utf8');
    } catch {
      /* missing counts as stale */
    }
    if (current !== source) stale.push(`stories/${name}.stories.ts`);
  } else {
    writeFileSync(out, source);
    written += 1;
  }
}

if (process.argv.includes('--check')) {
  if (stale.length > 0) {
    console.error(`Stories are out of date (${stale.length}):`);
    for (const s of stale) console.error(`  ${s}`);
    console.error('Run `pnpm -F @metocast/design-system stories`.');
    process.exit(1);
  }
  console.log(`All ${Object.keys(samples).filter((k) => !k.startsWith('$')).length} story files are current.`);
} else {
  console.log(`Wrote ${written} story files.`);
}
