#!/usr/bin/env node
// Writes one specification per component from three sources, so no part of it can drift:
//   - props, their types, defaults and doc comments, parsed from the component itself
//   - tokens consumed, parsed from the component's styles
//   - reference correspondence and deviations, read from tokens/fidelity.json
// The judgement — what the component is for, its anatomy, variants, keyboard map and ARIA — is
// hand-authored in docs/specs.json, because tooling cannot read intent.
//
// `--check` fails when a committed specification is out of date instead of rewriting it.
import { readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';
import { packageDir, root, tokensDir } from './tokens-lib.mjs';

const fidelity = JSON.parse(readFileSync(join(tokensDir, 'fidelity.json'), 'utf8'));
const measurements = JSON.parse(readFileSync(join(tokensDir, 'measurements.json'), 'utf8'));
const prose = JSON.parse(readFileSync(join(packageDir, 'docs/specs.json'), 'utf8'));
const tokens = JSON.parse(readFileSync(join(tokensDir, 'tokens.json'), 'utf8'));
const theme = JSON.parse(readFileSync(join(tokensDir, 'themes/sanctum.json'), 'utf8'));

const flat = new Map();
(function collect(node, path = []) {
  for (const [key, value] of Object.entries(node)) {
    if (key.startsWith('$')) continue;
    if (value && typeof value === 'object' && '$value' in value) flat.set([...path, key].join('-'), String(value.$value));
    else if (value && typeof value === 'object') collect(value, [...path, key]);
  }
})(tokens);

function resolve(name, seen = new Set()) {
  if (seen.has(name)) return '↺';
  seen.add(name);
  const raw = flat.get(name);
  // A semantic colour has one value per scheme, so both are shown rather than neither.
  if (raw === undefined) {
    const light = theme.light[name]?.$value;
    const dark = theme.dark[name]?.$value;
    return light ? `${light} / ${dark}` : '—';
  }
  const alias = /^\{([^}]+)\}$/.exec(raw.trim());
  return alias ? resolve(alias[1].replace(/\./g, '-'), seen) : raw;
}

const LENGTH = /(-?\d*\.?\d+)(px|rem|em|ms|s|%|vh|vw|dvh|svh|lvh|vmin|vmax|ch|ex|fr|deg)?/gi;
const strip = (v) =>
  v.replace(/\b(?:color-mix|rgba?|hsla?|oklch|oklab|var|cubic-bezier|steps|linear)\([^()]*(?:\([^()]*\)[^()]*)*\)/g, ' ');

const byKey = new Map();
for (const row of measurements.rows) {
  byKey.set(`${row.source}|${row.selector}|${row.property}|${row.breakpoint}`, row);
}

/** The `interface Props` block, with each prop's doc comment, type and default. */
function parseProps(source) {
  const block = /interface Props\s*{([\s\S]*?)\n  }/.exec(source);
  if (!block) return [];
  const defaults = new Map();
  const destructured = /let\s*{([\s\S]*?)}:\s*Props\s*=\s*\$props\(\)/.exec(source);
  if (destructured) {
    for (const part of destructured[1].split(/,\n/)) {
      const m = /^\s*(?:'([^']+)':\s*\w+|(\w+))(?:\s*=\s*([\s\S]+?))?\s*$/.exec(part.trim());
      if (m) defaults.set(m[1] ?? m[2], (m[3] ?? '').trim());
    }
  }

  const props = [];
  let comment = '';
  for (const raw of block[1].split('\n')) {
    const line = raw.trim();
    if (line.startsWith('/**') || line.startsWith('*') || line.startsWith('/*')) {
      comment += ' ' + line.replace(/^\/?\*+\/?/, '').replace(/\*\/$/, '').trim();
      continue;
    }
    const m = /^'?([\w-]+)'?(\?)?:\s*(.+?);$/.exec(line);
    if (m) {
      props.push({
        name: m[1],
        optional: Boolean(m[2]),
        type: m[3],
        default: defaults.get(m[1]) ?? '',
        note: comment.trim(),
      });
    }
    comment = '';
  }
  return props;
}

/** Every design token a component's styles reference, in the order they first appear. */
function parseTokens(source) {
  const style = /<style>([\s\S]*)<\/style>/.exec(source);
  if (!style) return [];
  const seen = new Set();
  for (const m of style[1].matchAll(/var\(--([a-z0-9-]+)/g)) {
    if (!m[1].startsWith('sanctum-')) seen.add(m[1]);
  }
  return [...seen].sort();
}

const escape = (v) => String(v).replace(/\|/g, '\\|');

function render(name, file, source) {
  const spec = prose[name];
  if (!spec) throw new Error(`docs/specs.json has no entry for ${name}`);
  const props = parseProps(source);
  const used = parseTokens(source);
  const entry = fidelity.components[name];

  const lines = [
    `<!-- GENERATED by scripts/build-docs.mjs from ${relative(root, file)}, docs/specs.json and tokens/fidelity.json. Edit those, not this. -->`,
    '',
    `# ${name}`,
    '',
    spec.purpose,
    '',
    '## Anatomy',
    '',
    spec.anatomy,
    '',
    '## Props',
    '',
  ];

  if (props.length === 0) lines.push('None.', '');
  else {
    lines.push('| Prop | Type | Default | Meaning |', '| --- | --- | --- | --- |');
    for (const prop of props) {
      lines.push(
        `| \`${prop.name}\`${prop.optional ? '' : ' *(required)*'} | \`${escape(prop.type)}\` | ${prop.default ? `\`${escape(prop.default)}\`` : '—'} | ${escape(prop.note) || '—'} |`,
      );
    }
    lines.push('');
  }

  lines.push('## Variants', '', spec.variants, '', '## States', '', spec.states, '', '## Tokens consumed', '');
  if (used.length === 0) lines.push('None — the component carries no styles of its own.', '');
  else {
    lines.push('| Token | Resolves to |', '| --- | --- |');
    for (const token of used) lines.push(`| \`--${token}\` | \`${escape(resolve(token))}\` |`);
    lines.push(
      '',
      'Every value resolves through a semantic or component token; `scripts/check-fidelity.mjs` fails on a literal.',
      '',
    );
  }

  lines.push('## Keyboard', '', spec.keyboard, '', '## ARIA', '', spec.aria, '', '## Accessibility acceptance criteria', '');
  lines.push(
    '- Reachable, operable and leavable by keyboard alone, with a focus indicator meeting 3:1 in both schemes.',
    '- An accessible name for every control, and current state exposed programmatically.',
    '- No meaning carried by colour alone.',
    '- Legible and operable at a 360px viewport and at desktop width, and at 200% zoom.',
    '- Interactive targets at least 44 × 44px on touch-capable viewports.',
  );
  for (const extra of spec.criteria ?? []) lines.push(`- ${extra}`);
  lines.push('', '## Reference correspondence', '');

  if (entry) {
    lines.push(
      `Source: \`${entry.source}\`.`,
      '',
      '| Selector | Property | Measured | Implemented | Token |',
      '| --- | --- | --- | --- | --- |',
    );
    for (const [token, map] of Object.entries(entry.tokens ?? {})) {
      const row = byKey.get(`${entry.source}|${map.selector}|${map.property}|${map.breakpoint ?? 'base'}`);
      const parts = row ? [...strip(row.value).matchAll(LENGTH)].map(([, n, u]) => (u ? `${parseFloat(n)}${u}` : String(parseFloat(n)))) : [];
      lines.push(
        `| \`${escape(map.selector)}\` | \`${map.property}\`${map.breakpoint ? ` @${map.breakpoint}` : ''} | \`${parts[map.index ?? 0] ?? '—'}\` | \`${escape(resolve(token))}\` | \`--${token}\` |`,
      );
    }
    lines.push('', 'Re-checked mechanically by `scripts/check-fidelity.mjs`.', '');
  } else {
    lines.push(
      spec.noReference ??
        'None. The reference has no counterpart; this component is designed in its idiom — hairline rules, square corners, mono micro-labels, the display face reserved for display type — and reviewed against its neighbours.',
      '',
    );
  }

  lines.push('## Recorded deviations', '');
  const deviations = Object.entries(entry?.deviations ?? {});
  const authored = spec.deviations ?? [];
  if (deviations.length === 0 && authored.length === 0) lines.push('None.', '');
  else {
    lines.push('| What | Why |', '| --- | --- |');
    for (const [token, why] of deviations) lines.push(`| \`--${token}\` | ${escape(why)} |`);
    for (const [what, why] of authored) lines.push(`| ${escape(what)} | ${escape(why)} |`);
    lines.push('');
  }

  return lines.join('\n');
}

function walk(dir, out = []) {
  for (const e of readdirSync(dir)) {
    const f = join(dir, e);
    if (statSync(f).isDirectory()) walk(f, out);
    else if (e.endsWith('.svelte')) out.push(f);
  }
  return out;
}

const files = ['src/primitives', 'src/patterns', 'src/a11y'].flatMap((d) => walk(join(packageDir, d)));
const stale = [];
let written = 0;

for (const file of files) {
  const name = file.split('/').pop().replace('.svelte', '');
  const markdown = render(name, file, readFileSync(file, 'utf8')) + '\n';
  const out = join(packageDir, `docs/${name}.md`);
  if (process.argv.includes('--check')) {
    let current = '';
    try {
      current = readFileSync(out, 'utf8');
    } catch {
      /* missing counts as stale */
    }
    if (current !== markdown) stale.push(`docs/${name}.md`);
  } else {
    writeFileSync(out, markdown);
    written += 1;
  }
}

if (process.argv.includes('--check')) {
  if (stale.length > 0) {
    console.error(`Specifications are out of date (${stale.length}):`);
    for (const s of stale) console.error(`  ${s}`);
    console.error('Run `pnpm -F @metocast/design-system docs`.');
    process.exit(1);
  }
  console.log(`All ${files.length} specifications are current.`);
} else {
  console.log(`Wrote ${written} specifications.`);
}
