#!/usr/bin/env node
// Emits packages/design-system/tokens/generated/tokens.css from the DTCG token source.
// `--check` diffs against the committed output instead of writing it.
import { readFileSync, writeFileSync } from 'node:fs';
import { flatten, loadTheme, outFile, primitives } from './tokens-lib.mjs';

const block = (selector, entries, indent = '\t') =>
  entries.length === 0
    ? ''
    : `${selector} {\n${entries.map(([n, v]) => `${indent}--${n}: ${v};`).join('\n')}\n}\n`;

const nest = (css) =>
  css
    .split('\n')
    .map((l) => (l ? `\t${l}` : l))
    .join('\n');

function emit() {
  const theme = loadTheme();
  const light = flatten(theme.light);
  const dark = flatten(theme.dark);

  const parts = [
    '/* GENERATED by scripts/build-tokens.mjs — do not edit. Run `pnpm -F @metocast/design-system tokens:build`. */\n',
    block(':root', flatten(primitives)),
    block(':root', light),
    // The attribute is authoritative, so the scheme can be switched without a reload.
    block(":root[data-scheme='dark']", dark),
    // Without an attribute the system preference decides, which is what a fresh install wants.
    `@media (prefers-color-scheme: dark) {\n${nest(block(":root:not([data-scheme='light'])", dark, '\t\t'))}}\n`,
  ];

  // Zeroing the duration primitives stills every semantic motion token that aliases them, which
  // removes the animation without removing any state indication.
  const stilled = flatten(primitives.duration ?? {}, ['duration']).map(([n]) => [n, '0ms']);
  parts.push(
    `@media (prefers-reduced-motion: reduce) {\n${nest(block(':root', stilled, '\t\t'))}}\n`,
  );

  return parts.filter(Boolean).join('\n');
}

const css = emit();

if (process.argv.includes('--check')) {
  if (readFileSync(outFile, 'utf8') !== css) {
    console.error(
      'tokens.css is out of date with the token source. Run `pnpm -F @metocast/design-system tokens:build`.',
    );
    process.exit(1);
  }
  console.log('tokens.css is up to date.');
} else {
  writeFileSync(outFile, css);
  console.log(`Wrote ${outFile}`);
}
