#!/usr/bin/env node
// Downloads the latin + latin-ext woff2 subsets the design needs into the package's
// static/fonts/ and writes the matching @font-face rules beside them. Nothing fetches a font at
// runtime — this exists so the bundled files can be regenerated.
import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { packageDir } from './tokens-lib.mjs';

const families = [
  'Cormorant+Garamond:ital,wght@0,400;0,500;0,600;1,400',
  'Inter+Tight:wght@400;500;600;700',
  'Geist+Mono:wght@400;500',
];
const wanted = new Set(['latin', 'latin-ext']);
const outDir = join(packageDir, 'static/fonts');
mkdirSync(outDir, { recursive: true });

const url = `https://fonts.googleapis.com/css2?${families.map((f) => `family=${f}`).join('&')}&display=swap`;
const css = await (
  await fetch(url, {
    headers: {
      'user-agent':
        'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120 Safari/537.36',
    },
  })
).text();

const rules = [];
let subset = null;
let current = {};
for (const line of css.split('\n')) {
  const comment = /^\/\*\s*(\S+)\s*\*\/$/.exec(line.trim());
  if (comment) subset = comment[1];
  const set = /^\s*([a-z-]+):\s*(.+);$/.exec(line);
  if (set) current[set[1]] = set[2];
  if (line.trim() === '}') {
    if (wanted.has(subset) && current.src) {
      const src = /url\((https:[^)]+)\)/.exec(current.src);
      const family = current['font-family'].replaceAll("'", '').replaceAll(' ', '');
      const style = current['font-style'] === 'italic' ? 'italic' : '';
      const file = `${family}-${current['font-weight']}${style}-${subset}.woff2`;
      const bytes = Buffer.from(await (await fetch(src[1])).arrayBuffer());
      writeFileSync(join(outDir, file), bytes);
      rules.push(
        [
          '@font-face {',
          `\tfont-family: ${current['font-family']};`,
          `\tfont-style: ${current['font-style']};`,
          `\tfont-weight: ${current['font-weight']};`,
          '\tfont-display: swap;',
          `\tsrc: url('./${file}') format('woff2');`,
          `\tunicode-range: ${current['unicode-range']};`,
          '}',
        ].join('\n'),
      );
      console.log(`${file} — ${(bytes.length / 1024).toFixed(1)} kB`);
    }
    current = {};
  }
}

writeFileSync(
  join(outDir, 'fonts.css'),
  `/* GENERATED by scripts/fetch-fonts.mjs — the woff2 files live beside this file. */\n\n${rules.join('\n\n')}\n`,
);
console.log(`Wrote ${rules.length} @font-face rules.`);
