#![recursion_limit = "256"]

#[cfg(desktop)]
pub mod bible;
mod commands;
mod logging;

// Models, database, server, and connectors are desktop-only.
#[cfg(desktop)]
mod broadlink;
#[cfg(desktop)]
pub mod connectors;
#[cfg(desktop)]
pub mod database;
#[cfg(desktop)]
mod models;
#[cfg(desktop)]
mod obs_devices;
#[cfg(desktop)]
pub mod queue;
#[cfg(desktop)]
pub mod runtime;
#[cfg(desktop)]
pub mod scheduler;
#[cfg(desktop)]
pub mod server;
#[cfg(desktop)]
pub(crate) mod uploader;

use std::sync::Arc;
use tauri::Manager;
use tauri_plugin_store::StoreExt;
use tokio::sync::RwLock;
use uuid::Uuid;

pub struct AppRuntime {
    pub mode: Option<String>,
    pub server_port: u16,
    pub client_url: Option<String>,
    pub auth_token: Arc<RwLock<String>>,
    /// Grants the desktop app read access to stored upstream credentials while it
    /// hosts the server. Regenerated every run — see `runtime::CoreOptions::admin_token`.
    #[cfg(desktop)]
    pub admin_token: Arc<String>,
    #[cfg(desktop)]
    pub obs_connector: Arc<connectors::obs::ObsConnector>,
    #[cfg(desktop)]
    pub blackmagic_camera_connector: Arc<connectors::blackmagic_camera::BlackmagicCameraConnector>,
    #[cfg(desktop)]
    pub vmix_connector: Arc<connectors::vmix::VmixConnector>,
    #[cfg(desktop)]
    pub atem_connector: Arc<connectors::atem::AtemConnector>,
    #[cfg(desktop)]
    pub broadlink_connector: Arc<connectors::broadlink::BroadlinkConnector>,
    #[cfg(desktop)]
    pub youtube_connector: Arc<connectors::youtube::YouTubeConnector>,
    #[cfg(desktop)]
    pub facebook_connector: Arc<connectors::facebook::FacebookConnector>,
    #[cfg(desktop)]
    pub discord_connector: Arc<connectors::discord::DiscordConnector>,
    #[cfg(target_os = "macos")]
    pub keynote_connector: Arc<connectors::keynote::KeynoteConnector>,
    /// Shared config Arcs — the same Arcs are injected into AppState so that
    /// saving config via Tauri command is immediately visible to Axum routes.
    #[cfg(desktop)]
    pub youtube_config: Arc<RwLock<connectors::YouTubeConfig>>,
    #[cfg(desktop)]
    pub facebook_config: Arc<RwLock<connectors::FacebookConfig>>,
    /// Shared OAuth state map — the same Arc is injected into AppState so that
    /// CSRF tokens generated by Tauri IPC commands are visible to the HTTP callback.
    #[cfg(desktop)]
    pub oauth_states: Arc<RwLock<std::collections::HashMap<String, (String, std::time::Instant)>>>,
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    let builder = tauri::Builder::default()
        .plugin(tauri_plugin_liquid_glass::init())
        .plugin(tauri_plugin_store::Builder::new().build())
        .plugin(tauri_plugin_deep_link::init())
        .plugin(tauri_plugin_native_nav::init())
        .plugin(tauri_plugin_opener::init());

    #[cfg(desktop)]
    let builder = builder.plugin(tauri_plugin_updater::Builder::new().build());

    #[cfg(desktop)]
    let builder = builder.plugin(tauri_plugin_dialog::init());

    // Pass generate_handler! directly into invoke_handler so the closure type
    // is inferred at the call site — storing it in a let binding loses the type.
    #[cfg(desktop)]
    let builder = builder.invoke_handler(tauri::generate_handler![
        commands::collections::save_bruno_collection,
        commands::token::get_token,
        commands::token::refresh_token,
        commands::server::get_server_port,
        commands::server::get_app_mode,
        commands::server::set_app_mode,
        commands::server::complete_setup,
        commands::server::get_client_url,
        commands::server::get_client_token,
        commands::server::get_admin_token,
        commands::server::can_host_server,
        commands::server::reset_setup,
        commands::server::get_local_host,
        commands::logs::get_application_log_path,
        commands::logs::read_application_log,
        commands::logs::download_application_log,
        commands::logs::remove_application_log,
        commands::logs::open_application_log,
        commands::updater::check_for_updates,
        commands::updater::install_update,
    ]);

    // Mobile is client-only — no server or Bruno collection commands.
    #[cfg(mobile)]
    let builder = builder.invoke_handler(tauri::generate_handler![
        commands::token::get_token,
        commands::token::refresh_token,
        commands::server::get_server_port,
        commands::server::get_app_mode,
        commands::server::set_app_mode,
        commands::server::complete_setup,
        commands::server::get_client_url,
        commands::server::get_client_token,
        commands::server::can_host_server,
        commands::server::reset_setup,
        commands::server::get_local_host,
        commands::logs::get_application_log_path,
        commands::logs::read_application_log,
        commands::logs::download_application_log,
        commands::logs::remove_application_log,
        commands::logs::open_application_log,
    ]);

    builder
        .setup(|app| {
            match logging::init_application_logging(&app.handle()) {
                Ok(path) => {
                    tracing::info!(log_path = %path.display(), "Application logging initialized");
                }
                Err(e) => {
                    eprintln!("Failed to initialize application logging: {e}");
                    logging::init_fallback_logging();
                    tracing::warn!("Application file logging unavailable: {e}");
                }
            }

            tracing::info!("Application setup started");

            // Load settings synchronously so AppRuntime is managed before the
            // UI can call any Tauri command.
            let store = app.store("app-settings.json")?;

            let mode = store.get("mode").and_then(|v| v.as_str().map(String::from));
            tracing::info!(
                mode = mode.as_deref().unwrap_or("unset"),
                "Application mode loaded"
            );

            // TAURI_AUTH_TOKEN env var overrides the stored token — used in CI
            // and local E2E testing so the token is predictable without needing
            // to read it from the Tauri store.
            let auth_token = if let Ok(env_token) = std::env::var("TAURI_AUTH_TOKEN") {
                env_token
            } else {
                match mode.as_deref() {
                    Some("client") => {
                        // In client mode the token is whatever the user entered
                        // during setup; complete_setup() saves it as "client_auth_token".
                        store
                            .get("client_auth_token")
                            .and_then(|v| v.as_str().map(String::from))
                            .unwrap_or_default()
                    }
                    _ => {
                        // In server mode (or not yet configured) generate/load our
                        // own auth token that incoming requests must present.
                        store
                            .get("auth_token")
                            .and_then(|v| v.as_str().map(String::from))
                            .unwrap_or_else(|| {
                                let t = Uuid::new_v4().to_string();
                                store.set("auth_token", serde_json::Value::String(t.clone()));
                                let _ = store.save();
                                t
                            })
                    }
                }
            };

            let client_url = store
                .get("server_url")
                .and_then(|v| v.as_str().map(String::from));

            let port: u16 = store
                .get("server_port")
                .and_then(|v| v.as_u64())
                .map(|p| p as u16)
                .unwrap_or(3737);

            let auth_token_arc = Arc::new(RwLock::new(auth_token));

            // Create connectors before AppRuntime so we can share the Arcs
            // with both the runtime and the server startup below.
            #[cfg(desktop)]
            let obs_connector = Arc::new(connectors::obs::ObsConnector::new());
            #[cfg(desktop)]
            let blackmagic_camera_connector =
                Arc::new(connectors::blackmagic_camera::BlackmagicCameraConnector::new());
            #[cfg(desktop)]
            let vmix_connector = Arc::new(connectors::vmix::VmixConnector::new());
            #[cfg(desktop)]
            let atem_connector = Arc::new(connectors::atem::AtemConnector::new());
            #[cfg(desktop)]
            let broadlink_connector = Arc::new(connectors::broadlink::BroadlinkConnector::new());
            #[cfg(desktop)]
            let youtube_connector = Arc::new(connectors::youtube::YouTubeConnector::new());
            #[cfg(desktop)]
            let facebook_connector = Arc::new(connectors::facebook::FacebookConnector::new());
            #[cfg(desktop)]
            let discord_connector = Arc::new(connectors::discord::DiscordConnector::new());
            #[cfg(target_os = "macos")]
            let keynote_connector = Arc::new(connectors::keynote::KeynoteConnector::new());

            // Config Arcs shared by AppRuntime and AppState. `runtime::start` fills
            // them from the database once the pool is up; until then they hold
            // defaults (client mode never uses them).
            #[cfg(desktop)]
            let yt_config_arc = Arc::new(RwLock::new(connectors::YouTubeConfig::default()));
            #[cfg(desktop)]
            let fb_config_arc = Arc::new(RwLock::new(connectors::FacebookConfig::default()));

            // Shared OAuth state map — the Tauri command and the Axum callback
            // handler both use the same Arc so CSRF tokens are visible to both.
            #[cfg(desktop)]
            let oauth_states_arc = Arc::new(RwLock::new(std::collections::HashMap::<
                String,
                (String, std::time::Instant),
            >::new()));

            let runtime = Arc::new(RwLock::new(AppRuntime {
                mode: mode.clone(),
                server_port: port,
                client_url,
                auth_token: auth_token_arc.clone(),
                #[cfg(desktop)]
                admin_token: Arc::new(
                    std::env::var("METOCAST_ADMIN_TOKEN")
                        .unwrap_or_else(|_| Uuid::new_v4().to_string()),
                ),
                #[cfg(desktop)]
                obs_connector: Arc::clone(&obs_connector),
                #[cfg(desktop)]
                blackmagic_camera_connector: Arc::clone(&blackmagic_camera_connector),
                #[cfg(desktop)]
                vmix_connector: Arc::clone(&vmix_connector),
                #[cfg(desktop)]
                atem_connector: Arc::clone(&atem_connector),
                #[cfg(desktop)]
                broadlink_connector: Arc::clone(&broadlink_connector),
                #[cfg(desktop)]
                youtube_connector: Arc::clone(&youtube_connector),
                #[cfg(desktop)]
                facebook_connector: Arc::clone(&facebook_connector),
                #[cfg(desktop)]
                discord_connector: Arc::clone(&discord_connector),
                #[cfg(target_os = "macos")]
                keynote_connector: Arc::clone(&keynote_connector),
                #[cfg(desktop)]
                youtube_config: Arc::clone(&yt_config_arc),
                #[cfg(desktop)]
                facebook_config: Arc::clone(&fb_config_arc),
                #[cfg(desktop)]
                oauth_states: Arc::clone(&oauth_states_arc),
            }));

            // Managed here — guaranteed to exist before any invoke() call.
            app.manage(runtime.clone());

            // Only start the server if mode was already configured as "server".
            // Server mode is desktop-only (requires embedded PostgreSQL + Axum).
            #[cfg(desktop)]
            if mode.as_deref() == Some("server") {
                tracing::info!(port, "Server mode detected; starting backend");
                let handle = app.handle().clone();
                let runtime_clone = Arc::clone(&runtime);
                tauri::async_runtime::spawn(async move {
                    if let Err(e) = runtime::start_from_app_runtime(&runtime_clone, handle).await {
                        tracing::error!("Backend startup failed: {e}");
                    }
                });
            }

            // YouTube and Facebook connectors require the DB pool (for token loading)
            // and are therefore started inside runtime::start(), after the pool is ready.

            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
