mod bible;
mod commands;

// Models, database, server, and connectors are desktop-only.
#[cfg(desktop)]
mod models;
#[cfg(desktop)]
mod database;
#[cfg(desktop)]
mod server;
#[cfg(desktop)]
mod connectors;
#[cfg(desktop)]
mod mediamtx;
#[cfg(desktop)]
mod scheduler;

use std::sync::Arc;
use tauri::Manager;
use tauri_plugin_store::StoreExt;
use tokio::sync::RwLock;
use uuid::Uuid;

#[cfg(desktop)]
use connectors::ConnectorConfig;

pub struct AppRuntime {
    pub mode: Option<String>,
    pub server_port: u16,
    pub client_url: Option<String>,
    pub auth_token: Arc<RwLock<String>>,
    #[cfg(desktop)]
    pub obs_connector: Arc<connectors::obs::ObsConnector>,
    #[cfg(desktop)]
    pub vmix_connector: Arc<connectors::vmix::VmixConnector>,
    #[cfg(desktop)]
    pub atem_connector: Arc<connectors::atem::AtemConnector>,
    #[cfg(desktop)]
    pub broadlink_connector: Arc<connectors::broadlink::BroadlinkConnector>,
    #[cfg(desktop)]
    pub youtube_connector: Arc<connectors::youtube::YouTubeConnector>,
    #[cfg(desktop)]
    pub facebook_connector: Arc<connectors::facebook::FacebookConnector>,
    #[cfg(desktop)]
    pub discord_connector: Arc<connectors::discord::DiscordConnector>,
    /// Shared config Arcs — the same Arcs are injected into AppState so that
    /// saving config via Tauri command is immediately visible to Axum routes.
    #[cfg(desktop)]
    pub youtube_config: Arc<RwLock<connectors::YouTubeConfig>>,
    #[cfg(desktop)]
    pub facebook_config: Arc<RwLock<connectors::FacebookConfig>>,
    /// Shared OAuth state map — the same Arc is injected into AppState so that
    /// CSRF tokens generated by Tauri IPC commands are visible to the HTTP callback.
    #[cfg(desktop)]
    pub oauth_states: Arc<RwLock<std::collections::HashMap<String, (String, std::time::Instant)>>>,
    #[cfg(desktop)]
    pub mediamtx_manager: Arc<mediamtx::MediamtxManager>,
    #[cfg(desktop)]
    pub relay_config: Arc<RwLock<mediamtx::RelayConfig>>,
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    let builder = tauri::Builder::default()
        .plugin(tauri_plugin_store::Builder::new().build())
        .plugin(tauri_plugin_opener::init());

    #[cfg(desktop)]
    let builder = builder.plugin(tauri_plugin_dialog::init());

    // Pass generate_handler! directly into invoke_handler so the closure type
    // is inferred at the call site — storing it in a let binding loses the type.
    #[cfg(desktop)]
    let builder = builder.invoke_handler(tauri::generate_handler![
        bible::fetch_bible_v2,
        bible::fetch_bible_suggestions,
        bible::fetch_bible_legacy,
        commands::collections::save_bruno_collection,
        commands::token::get_token,
        commands::token::refresh_token,
        commands::server::get_server_port,
        commands::server::get_app_mode,
        commands::server::set_app_mode,
        commands::server::complete_setup,
        commands::server::get_client_url,
        commands::server::get_client_token,
        commands::server::reset_setup,
        commands::server::get_local_ip,
        commands::connectors::get_obs_config,
        commands::connectors::save_obs_config,
        commands::connectors::get_obs_status,
        commands::connectors::connect_obs,
        commands::connectors::disconnect_obs,
        commands::connectors::get_vmix_config,
        commands::connectors::save_vmix_config,
        commands::connectors::get_vmix_status,
        commands::connectors::get_atem_config,
        commands::connectors::save_atem_config,
        commands::connectors::get_atem_status,
        commands::connectors::get_broadlink_config,
        commands::connectors::save_broadlink_config,
        commands::connectors::get_broadlink_status,
        commands::connectors::get_discord_config,
        commands::connectors::save_discord_config,
        commands::connectors::get_discord_status,
        commands::connectors::get_youtube_config,
        commands::connectors::save_youtube_config,
        commands::connectors::get_youtube_status,
        commands::connectors::get_youtube_auth_url,
        commands::connectors::youtube_logout,
        commands::connectors::get_facebook_config,
        commands::connectors::save_facebook_config,
        commands::connectors::get_facebook_status,
        commands::connectors::get_facebook_auth_url,
        commands::connectors::facebook_logout,
        commands::connectors::get_relay_config,
        commands::connectors::save_relay_config,
        commands::connectors::get_obs_stream_settings,
        commands::connectors::set_obs_stream_settings,
    ]);

    // Mobile is client-only — no server or Bruno collection commands.
    #[cfg(mobile)]
    let builder = builder.invoke_handler(tauri::generate_handler![
        bible::fetch_bible_v2,
        bible::fetch_bible_suggestions,
        bible::fetch_bible_legacy,
        commands::token::get_token,
        commands::token::refresh_token,
        commands::server::get_server_port,
        commands::server::get_app_mode,
        commands::server::set_app_mode,
        commands::server::complete_setup,
        commands::server::get_client_url,
        commands::server::get_client_token,
        commands::server::reset_setup,
        commands::server::get_local_ip,
    ]);

    builder
        .setup(|app| {
            tracing_subscriber::fmt()
                .with_env_filter(
                    tracing_subscriber::EnvFilter::try_from_default_env()
                        .unwrap_or_else(|_| "info".into()),
                )
                .init();

            // Load settings synchronously so AppRuntime is managed before the
            // UI can call any Tauri command.
            let store = app.store("app-settings.json")?;

            let mode = store
                .get("mode")
                .and_then(|v| v.as_str().map(String::from));

            let auth_token = store
                .get("auth_token")
                .and_then(|v| v.as_str().map(String::from))
                .unwrap_or_else(|| {
                    let t = Uuid::new_v4().to_string();
                    store.set("auth_token", serde_json::Value::String(t.clone()));
                    let _ = store.save();
                    t
                });

            let client_url = store
                .get("server_url")
                .and_then(|v| v.as_str().map(String::from));

            let port: u16 = store
                .get("server_port")
                .and_then(|v| v.as_u64())
                .map(|p| p as u16)
                .unwrap_or(3737);

            let auth_token_arc = Arc::new(RwLock::new(auth_token));

            // Create connectors before AppRuntime so we can share the Arcs
            // with both the runtime and the server startup below.
            #[cfg(desktop)]
            let obs_connector = Arc::new(connectors::obs::ObsConnector::new());
            #[cfg(desktop)]
            let vmix_connector = Arc::new(connectors::vmix::VmixConnector::new());
            #[cfg(desktop)]
            let atem_connector = Arc::new(connectors::atem::AtemConnector::new());
            #[cfg(desktop)]
            let broadlink_connector = Arc::new(connectors::broadlink::BroadlinkConnector::new());
            #[cfg(desktop)]
            let youtube_connector = Arc::new(connectors::youtube::YouTubeConnector::new());
            #[cfg(desktop)]
            let facebook_connector = Arc::new(connectors::facebook::FacebookConnector::new());
            #[cfg(desktop)]
            let discord_connector = Arc::new(connectors::discord::DiscordConnector::new());

            // Config Arcs created here so both AppRuntime (Tauri) and AppState
            // (Axum) hold the same Arc — writing via a Tauri command is
            // immediately visible to OAuth routes without any IPC round-trip.
            #[cfg(desktop)]
            let yt_config_arc = {
                let cfg: connectors::YouTubeConfig = store
                    .get("youtube_config")
                    .and_then(|v| serde_json::from_value(v).ok())
                    .unwrap_or_default();
                Arc::new(RwLock::new(cfg))
            };
            #[cfg(desktop)]
            let fb_config_arc = {
                let cfg: connectors::FacebookConfig = store
                    .get("facebook_config")
                    .and_then(|v| serde_json::from_value(v).ok())
                    .unwrap_or_default();
                Arc::new(RwLock::new(cfg))
            };

            // Shared OAuth state map — the Tauri command and the Axum callback
            // handler both use the same Arc so CSRF tokens are visible to both.
            #[cfg(desktop)]
            let oauth_states_arc = Arc::new(RwLock::new(
                std::collections::HashMap::<String, (String, std::time::Instant)>::new(),
            ));

            #[cfg(desktop)]
            let mediamtx_manager = Arc::new(mediamtx::MediamtxManager::new());

            #[cfg(desktop)]
            let relay_config_arc = {
                let cfg: mediamtx::RelayConfig = store
                    .get("relay_config")
                    .and_then(|v| serde_json::from_value(v).ok())
                    .unwrap_or_default();
                Arc::new(RwLock::new(cfg))
            };

            let runtime = Arc::new(RwLock::new(AppRuntime {
                mode: mode.clone(),
                server_port: port,
                client_url,
                auth_token: auth_token_arc.clone(),
                #[cfg(desktop)]
                obs_connector: Arc::clone(&obs_connector),
                #[cfg(desktop)]
                vmix_connector: Arc::clone(&vmix_connector),
                #[cfg(desktop)]
                atem_connector: Arc::clone(&atem_connector),
                #[cfg(desktop)]
                broadlink_connector: Arc::clone(&broadlink_connector),
                #[cfg(desktop)]
                youtube_connector: Arc::clone(&youtube_connector),
                #[cfg(desktop)]
                facebook_connector: Arc::clone(&facebook_connector),
                #[cfg(desktop)]
                discord_connector: Arc::clone(&discord_connector),
                #[cfg(desktop)]
                youtube_config: Arc::clone(&yt_config_arc),
                #[cfg(desktop)]
                facebook_config: Arc::clone(&fb_config_arc),
                #[cfg(desktop)]
                oauth_states: Arc::clone(&oauth_states_arc),
                #[cfg(desktop)]
                mediamtx_manager: Arc::clone(&mediamtx_manager),
                #[cfg(desktop)]
                relay_config: Arc::clone(&relay_config_arc),
            }));

            // Managed here — guaranteed to exist before any invoke() call.
            app.manage(runtime.clone());

            // Only start the server if mode was already configured as "server".
            // Server mode is desktop-only (requires embedded PostgreSQL + Axum).
            #[cfg(desktop)]
            if mode.as_deref() == Some("server") {
                let handle = app.handle().clone();
                let obs = Arc::clone(&obs_connector);
                let vmix = Arc::clone(&vmix_connector);
                let yt = Arc::clone(&youtube_connector);
                let fb = Arc::clone(&facebook_connector);
                // Pass the shared config Arcs so AppState uses the same Arcs
                // as AppRuntime — updates from Tauri commands are visible immediately.
                let yt_cfg = Arc::clone(&yt_config_arc);
                let fb_cfg = Arc::clone(&fb_config_arc);
                let oauth = Arc::clone(&oauth_states_arc);

                tauri::async_runtime::spawn(async move {
                    if let Err(e) = start_server(handle, auth_token_arc, port, obs, vmix, yt, fb, yt_cfg, fb_cfg, oauth).await {
                        tracing::error!("Backend startup failed: {e}");
                    }
                });
            }

            // Start mediamtx sidecar in server mode so clients can receive the
            // OBS stream via WebRTC. Failure is non-fatal — the app continues
            // without the preview feature (e.g. binary not yet downloaded).
            #[cfg(desktop)]
            if mode.as_deref() == Some("server") {
                let mgr = Arc::clone(&mediamtx_manager);
                let relay_cfg = Arc::clone(&relay_config_arc);
                let handle = app.handle().clone();
                tauri::async_runtime::spawn(async move {
                    let data_dir = handle
                        .path()
                        .app_data_dir()
                        .unwrap_or_else(|_| std::path::PathBuf::from("./data"));
                    let relay = relay_cfg.read().await.clone();
                    if let Err(e) = mgr.start(&handle, &data_dir, &relay).await {
                        tracing::warn!("mediamtx could not start: {e}");
                    }
                });
            }

            // Auto-start OBS connector if previously configured as enabled.
            #[cfg(desktop)]
            {
                let obs_config: connectors::ObsConfig = store
                    .get("obs_config")
                    .and_then(|v| serde_json::from_value(v).ok())
                    .unwrap_or_default();

                if obs_config.is_configured() {
                    let runtime_clone = Arc::clone(&runtime);
                    let handle = app.handle().clone();
                    tauri::async_runtime::spawn(async move {
                        let obs_connector = {
                            let rt = runtime_clone.read().await;
                            Arc::clone(&rt.obs_connector)
                        };
                        obs_connector.start(obs_config, handle).await;
                    });
                }
            }

            // YouTube and Facebook connectors require the DB pool (for token loading)
            // and are therefore started inside start_server(), after the pool is ready.

            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}

#[cfg(desktop)]
pub(crate) async fn start_server(
    app: tauri::AppHandle,
    auth_token: Arc<RwLock<String>>,
    port: u16,
    obs_connector: Arc<connectors::obs::ObsConnector>,
    vmix_connector: Arc<connectors::vmix::VmixConnector>,
    youtube_connector: Arc<connectors::youtube::YouTubeConnector>,
    facebook_connector: Arc<connectors::facebook::FacebookConnector>,
    youtube_config: Arc<RwLock<connectors::YouTubeConfig>>,
    facebook_config: Arc<RwLock<connectors::FacebookConfig>>,
    oauth_states: Arc<RwLock<std::collections::HashMap<String, (String, std::time::Instant)>>>,
) -> anyhow::Result<()> {
    use std::path::PathBuf;

    let data_dir = app
        .path()
        .app_data_dir()
        .unwrap_or_else(|_| PathBuf::from("./data"));

    tracing::info!("Starting embedded PostgreSQL in {data_dir:?}");
    let embedded = database::embedded::EmbeddedDb::start(data_dir).await?;
    let connection_url = embedded.connection_url.clone();

    tracing::info!("Connecting pool to {connection_url}");
    let pool = database::create_pool(&connection_url).await?;

    tracing::info!("Running migrations");
    database::run_migrations(&pool).await?;

    // Auto-start social connectors now that the pool is available.
    // Connectors check for stored tokens and stay Disconnected if none exist.
    {
        let yt_cfg = youtube_config.read().await.clone();
        if yt_cfg.is_configured() {
            youtube_connector.start(pool.clone(), yt_cfg, app.clone()).await;
        }
    }
    {
        let fb_cfg = facebook_config.read().await.clone();
        if fb_cfg.is_configured() {
            facebook_connector.start(pool.clone(), app.clone()).await;
        }
    }

    let static_dir = app
        .path()
        .resource_dir()
        .ok()
        .map(|p| p.join("_up_").to_string_lossy().into_owned());

    let cron_scheduler = Arc::new(scheduler::CronScheduler::new());

    tracing::info!("Starting Axum on port {port}");
    server::build_and_serve(
        pool,
        auth_token,
        connection_url,
        port,
        static_dir,
        obs_connector,
        vmix_connector,
        youtube_connector,
        facebook_connector,
        youtube_config,
        facebook_config,
        oauth_states,
        app.clone(),
        cron_scheduler,
    )
    .await?;

    embedded.stop().await?;

    Ok(())
}
