// GENERATED by scripts/build-stories.mjs from stories/samples.json. Edit that, not this.
import type { Meta, StoryObj } from '@storybook/svelte-vite';
import Badge from '../src/primitives/Badge.svelte';
import Anatomy from './support/Anatomy.svelte';
import { s } from './support/snippet.js';

const meta = {
  title: 'Primitives/Badge',
  component: Badge,
  tags: ['autodocs'],
  parameters: {
    docs: { description: { component: 'Specification: docs/Badge.md' } },
  },
} satisfies Meta<Badge>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Neutral: Story = {
  args: {
    children: s('12 elem'),
    tone: "neutral",
  },
};

export const Live: Story = {
  args: {
    children: s('Adásban'),
    tone: "live",
    dot: true,
  },
};

export const Ok: Story = {
  args: {
    children: s('Kapcsolódva'),
    tone: "ok",
    dot: true,
  },
};

export const Warn: Story = {
  args: {
    children: s('Késleltetés'),
    tone: "warn",
    dot: true,
  },
};

export const Error: Story = {
  args: {
    children: s('Megszakadt'),
    tone: "error",
    dot: true,
  },
};

export const Off: Story = {
  args: {
    children: s('Készenlét'),
    tone: "off",
    dot: true,
  },
};

/** The component beside the reference declarations its values were taken from. */
export const Anatomy_: Story = {
  name: 'Anatomy & reference',
  render: () => ({ Component: Anatomy, props: { component: 'Badge' } }),
};
