// GENERATED by scripts/build-stories.mjs from stories/samples.json. Edit that, not this.
import type { Meta, StoryObj } from '@storybook/svelte-vite';
import Button from '../src/primitives/Button.svelte';
import Anatomy from './support/Anatomy.svelte';
import { s } from './support/snippet.js';

const meta = {
  title: 'Primitives/Button',
  component: Button,
  tags: ['autodocs'],
  parameters: {
    docs: { description: { component: 'Specification: docs/Button.md' } },
  },
} satisfies Meta<Button>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Primary: Story = {
  args: {
    children: s('Mentés'),
    variant: 'primary',
  },
};

export const Secondary: Story = {
  args: {
    children: s('Mégse'),
    variant: 'secondary',
  },
};

export const Danger: Story = {
  args: {
    children: s('Esemény törlése'),
    variant: 'danger',
  },
};

export const Quiet: Story = {
  args: {
    children: s('Összes törlése'),
    variant: 'quiet',
  },
};

export const Block: Story = {
  args: {
    children: s('Mentés'),
    variant: 'primary',
    block: true,
  },
};

export const Disabled: Story = {
  args: {
    children: s('Mentés'),
    variant: 'primary',
    disabled: true,
  },
};

export const Loading: Story = {
  args: {
    children: s('Mentés'),
    variant: 'primary',
    loading: true,
    loadingLabel: 'Mentés folyamatban',
  },
};

/** The component beside the reference declarations its values were taken from. */
export const Anatomy_: Story = {
  name: 'Anatomy & reference',
  render: () => ({ Component: Anatomy, props: { component: 'Button' } }),
};
