// GENERATED by scripts/build-stories.mjs from stories/samples.json. Edit that, not this.
import type { Meta, StoryObj } from '@storybook/svelte-vite';
import Checkbox from '../src/primitives/Checkbox.svelte';
import Anatomy from './support/Anatomy.svelte';

const meta = {
  title: 'Primitives/Checkbox',
  component: Checkbox,
  tags: ['autodocs'],
  parameters: {
    docs: { description: { component: 'Specification: docs/Checkbox.md' } },
  },
} satisfies Meta<Checkbox>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {
    label: "Felvétel indítása az adással együtt",
  },
};

export const Checked: Story = {
  args: {
    label: "Felvétel indítása az adással együtt",
    checked: true,
  },
};

export const Indeterminate: Story = {
  args: {
    label: "Felvétel indítása az adással együtt",
    indeterminate: true,
  },
};

export const Disabled: Story = {
  args: {
    label: "Felvétel indítása az adással együtt",
    disabled: true,
    checked: true,
  },
};

export const WithDescription: Story = {
  args: {
    label: "Automatikus feltöltés",
    describedby: "cb-hint",
  },
};

/** The component beside the reference declarations its values were taken from. */
export const Anatomy_: Story = {
  name: 'Anatomy & reference',
  render: () => ({ Component: Anatomy, props: { component: 'Checkbox' } }),
};
