// GENERATED by scripts/build-stories.mjs from stories/samples.json. Edit that, not this.
import type { Meta, StoryObj } from '@storybook/svelte-vite';
import DateBlock from '../src/primitives/DateBlock.svelte';
import Anatomy from './support/Anatomy.svelte';

const meta = {
  title: 'Primitives/DateBlock',
  component: DateBlock,
  tags: ['autodocs'],
  parameters: {
    docs: { description: { component: 'Specification: docs/DateBlock.md' } },
  },
} satisfies Meta<DateBlock>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {
    month: 'MÁR',
    day: 14,
    label: '2026. március 14.',
  },
};

export const TwoDigitDay: Story = {
  args: {
    month: 'MÁR',
    day: 30,
    label: '2026. március 30.',
  },
};

export const Undescribed: Story = {
  args: {
    month: 'MÁR',
    day: 14,
    label: undefined,
  },
};

/** The component beside the reference declarations its values were taken from. */
export const Anatomy_: Story = {
  name: 'Anatomy & reference',
  render: () => ({ Component: Anatomy, props: { component: 'DateBlock' } }),
};
