// GENERATED by scripts/build-stories.mjs from stories/samples.json. Edit that, not this.
import type { Meta, StoryObj } from '@storybook/svelte-vite';
import DeviceList from '../src/patterns/DeviceList.svelte';
import Anatomy from './support/Anatomy.svelte';

const meta = {
  title: 'Patterns/DeviceList',
  component: DeviceList,
  tags: ['autodocs'],
  parameters: {
    docs: { description: { component: 'Specification: docs/DeviceList.md' } },
  },
} satisfies Meta<DeviceList>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {
    label: "Talált eszközök",
    actionLabel: "Párosítás",
    emptyMessage: "Egy eszköz sem válaszolt.",
    devices: [
      {
        id: "a",
        name: "Nappali RM4 Pro",
        address: "192.168.1.42",
        kind: "Broadlink RM4 Pro",
      },
      {
        id: "b",
        name: "Karzat RM Mini",
        address: "192.168.1.51",
        kind: "Broadlink RM Mini 3",
      },
    ],
  },
};

export const Empty: Story = {
  args: {
    label: "Talált eszközök",
    actionLabel: "Párosítás",
    emptyMessage: "Egy eszköz sem válaszolt.",
    devices: [],
  },
};

/** The component beside the reference declarations its values were taken from. */
export const Anatomy_: Story = {
  name: 'Anatomy & reference',
  render: () => ({ Component: Anatomy, props: { component: 'DeviceList' } }),
};
