// GENERATED by scripts/build-stories.mjs from stories/samples.json. Edit that, not this.
import type { Meta, StoryObj } from '@storybook/svelte-vite';
import Dialog from '../src/patterns/Dialog.svelte';
import Anatomy from './support/Anatomy.svelte';
import { s } from './support/snippet.js';

const meta = {
  title: 'Patterns/Dialog',
  component: Dialog,
  tags: ['autodocs'],
  parameters: {
    docs: { description: { component: 'Specification: docs/Dialog.md' } },
  },
} satisfies Meta<Dialog>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {
    open: true,
    eyebrow: "Megerősítés",
    title: "Törlöd az eseményt?",
    children: s('Az esemény és minden hozzá tartozó felvétel eltűnik. Ez nem vonható vissza.'),
  },
};

export const ModalOnly: Story = {
  args: {
    open: true,
    eyebrow: "Megerősítés",
    title: "Törlöd az eseményt?",
    children: s('Az esemény és minden hozzá tartozó felvétel eltűnik. Ez nem vonható vissza.'),
    modalOnly: true,
  },
};

export const Closed: Story = {
  args: {
    open: false,
    eyebrow: "Megerősítés",
    title: "Törlöd az eseményt?",
    children: s('Az esemény és minden hozzá tartozó felvétel eltűnik. Ez nem vonható vissza.'),
  },
};

/** The component beside the reference declarations its values were taken from. */
export const Anatomy_: Story = {
  name: 'Anatomy & reference',
  render: () => ({ Component: Anatomy, props: { component: 'Dialog' } }),
};
