// GENERATED by scripts/build-stories.mjs from stories/samples.json. Edit that, not this.
import type { Meta, StoryObj } from '@storybook/svelte-vite';
import DiscoveryPanel from '../src/patterns/DiscoveryPanel.svelte';
import Anatomy from './support/Anatomy.svelte';
import { s } from './support/snippet.js';

const meta = {
  title: 'Patterns/DiscoveryPanel',
  component: DiscoveryPanel,
  tags: ['autodocs'],
  parameters: {
    docs: { description: { component: 'Specification: docs/DiscoveryPanel.md' } },
  },
} satisfies Meta<DiscoveryPanel>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {
    title: "Broadlink eszközök",
    description: "A hálózaton található infravörös és rádiós vezérlők.",
    scanLabel: "Keresés",
    children: s('Két eszköz válaszolt.'),
  },
};

export const Scanning: Story = {
  args: {
    title: "Broadlink eszközök",
    description: "A hálózaton található infravörös és rádiós vezérlők.",
    scanLabel: "Keresés",
    children: s('Két eszköz válaszolt.'),
    scanning: true,
    scanningLabel: "Keresés folyamatban",
  },
};

/** The component beside the reference declarations its values were taken from. */
export const Anatomy_: Story = {
  name: 'Anatomy & reference',
  render: () => ({ Component: Anatomy, props: { component: 'DiscoveryPanel' } }),
};
