// GENERATED by scripts/build-stories.mjs from stories/samples.json. Edit that, not this.
import type { Meta, StoryObj } from '@storybook/svelte-vite';
import Dot from '../src/primitives/Dot.svelte';
import Anatomy from './support/Anatomy.svelte';

const meta = {
  title: 'Primitives/Dot',
  component: Dot,
  tags: ['autodocs'],
  parameters: {
    docs: { description: { component: 'Specification: docs/Dot.md' } },
  },
} satisfies Meta<Dot>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {

  },
};

export const Live: Story = {
  args: {
    color: 'var(--status-live)',
    pulse: true,
  },
};

export const Ok: Story = {
  args: {
    color: 'var(--status-ok)',
  },
};

export const Off: Story = {
  args: {
    color: 'var(--status-off)',
  },
};

export const Large: Story = {
  args: {
    size: 12,
  },
};

/** The component beside the reference declarations its values were taken from. */
export const Anatomy_: Story = {
  name: 'Anatomy & reference',
  render: () => ({ Component: Anatomy, props: { component: 'Dot' } }),
};
