// GENERATED by scripts/build-stories.mjs from stories/samples.json. Edit that, not this.
import type { Meta, StoryObj } from '@storybook/svelte-vite';
import EmptyState from '../src/patterns/EmptyState.svelte';
import Anatomy from './support/Anatomy.svelte';

const meta = {
  title: 'Patterns/EmptyState',
  component: EmptyState,
  tags: ['autodocs'],
  parameters: {
    docs: { description: { component: 'Specification: docs/EmptyState.md' } },
  },
} satisfies Meta<EmptyState>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {
    title: 'Csend van a vezérlőben.',
    hint: 'A csatlakozók itt szólalnak meg',
  },
};

export const TitleOnly: Story = {
  args: {
    title: 'Csend van a vezérlőben.',
    hint: '',
  },
};

/** The component beside the reference declarations its values were taken from. */
export const Anatomy_: Story = {
  name: 'Anatomy & reference',
  render: () => ({ Component: Anatomy, props: { component: 'EmptyState' } }),
};
