// GENERATED by scripts/build-stories.mjs from stories/samples.json. Edit that, not this.
import type { Meta, StoryObj } from '@storybook/svelte-vite';
import ErrorState from '../src/patterns/ErrorState.svelte';
import Anatomy from './support/Anatomy.svelte';

const meta = {
  title: 'Patterns/ErrorState',
  component: ErrorState,
  tags: ['autodocs'],
  parameters: {
    docs: { description: { component: 'Specification: docs/ErrorState.md' } },
  },
} satisfies Meta<ErrorState>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {
    title: "Nem sikerült betölteni",
    body: "A kiszolgáló nem válaszolt időben. Ellenőrizd, hogy fut-e, majd próbáld újra.",
  },
};

export const WithRetry: Story = {
  args: {
    title: "Nem sikerült betölteni",
    body: "A kiszolgáló nem válaszolt időben. Ellenőrizd, hogy fut-e, majd próbáld újra.",
    retryLabel: "Újra",
    onretry: () => {},
  },
};

export const TitleOnly: Story = {
  args: {
    title: "Nem sikerült betölteni",
    body: "",
  },
};

/** The component beside the reference declarations its values were taken from. */
export const Anatomy_: Story = {
  name: 'Anatomy & reference',
  render: () => ({ Component: Anatomy, props: { component: 'ErrorState' } }),
};
