// GENERATED by scripts/build-stories.mjs from stories/samples.json. Edit that, not this.
import type { Meta, StoryObj } from '@storybook/svelte-vite';
import Field from '../src/primitives/Field.svelte';
import Anatomy from './support/Anatomy.svelte';

const meta = {
  title: 'Primitives/Field',
  component: Field,
  tags: ['autodocs'],
  parameters: {
    docs: { description: { component: 'Specification: docs/Field.md' } },
  },
} satisfies Meta<Field>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {
    label: 'Esemény neve',
    value: 'Vasárnapi istentisztelet',
  },
};

export const WithHint: Story = {
  args: {
    label: 'Esemény neve',
    value: 'Vasárnapi istentisztelet',
    hint: 'Ez jelenik meg a közvetítés címeként',
  },
};

export const Empty: Story = {
  args: {
    label: 'Esemény neve',
    value: '',
    placeholder: 'Add meg a nevet',
  },
};

export const Invalid: Story = {
  args: {
    label: 'Esemény neve',
    value: '',
    error: 'A név nem lehet üres',
  },
};

export const Readonly: Story = {
  args: {
    label: 'Esemény neve',
    value: 'Vasárnapi istentisztelet',
    readonly: true,
  },
};

export const Disabled: Story = {
  args: {
    label: 'Esemény neve',
    value: 'Vasárnapi istentisztelet',
    disabled: true,
  },
};

/** The component beside the reference declarations its values were taken from. */
export const Anatomy_: Story = {
  name: 'Anatomy & reference',
  render: () => ({ Component: Anatomy, props: { component: 'Field' } }),
};
