// GENERATED by scripts/build-stories.mjs from stories/samples.json. Edit that, not this.
import type { Meta, StoryObj } from '@storybook/svelte-vite';
import FlameMark from '../src/primitives/FlameMark.svelte';
import Anatomy from './support/Anatomy.svelte';

const meta = {
  title: 'Primitives/FlameMark',
  component: FlameMark,
  tags: ['autodocs'],
  parameters: {
    docs: { description: { component: 'Specification: docs/FlameMark.md' } },
  },
} satisfies Meta<FlameMark>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {

  },
};

export const Large: Story = {
  args: {
    size: 64,
  },
};

export const Labelled: Story = {
  args: {
    label: "Metocast",
  },
};

/** The component beside the reference declarations its values were taken from. */
export const Anatomy_: Story = {
  name: 'Anatomy & reference',
  render: () => ({ Component: Anatomy, props: { component: 'FlameMark' } }),
};
