// GENERATED by scripts/build-stories.mjs from stories/samples.json. Edit that, not this.
import type { Meta, StoryObj } from '@storybook/svelte-vite';
import FormSection from '../src/patterns/FormSection.svelte';
import Anatomy from './support/Anatomy.svelte';
import { s } from './support/snippet.js';

const meta = {
  title: 'Patterns/FormSection',
  component: FormSection,
  tags: ['autodocs'],
  parameters: {
    docs: { description: { component: 'Specification: docs/FormSection.md' } },
  },
} satisfies Meta<FormSection>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {
    number: '01',
    label: 'Alapadatok',
    children: s('A szakasz tartalma'),
  },
};

export const WithHint: Story = {
  args: {
    number: '01',
    label: 'Alapadatok',
    children: s('A szakasz tartalma'),
    hint: 'Kötelező',
  },
};

export const Last: Story = {
  args: {
    number: '04',
    label: 'Közvetítés',
    children: s('A szakasz tartalma'),
    last: true,
  },
};

/** The component beside the reference declarations its values were taken from. */
export const Anatomy_: Story = {
  name: 'Anatomy & reference',
  render: () => ({ Component: Anatomy, props: { component: 'FormSection' } }),
};
