// GENERATED by scripts/build-stories.mjs from stories/samples.json. Edit that, not this.
import type { Meta, StoryObj } from '@storybook/svelte-vite';
import Glyph from '../src/primitives/Glyph.svelte';
import Anatomy from './support/Anatomy.svelte';

const meta = {
  title: 'Primitives/Glyph',
  component: Glyph,
  tags: ['autodocs'],
  parameters: {
    docs: { description: { component: 'Specification: docs/Glyph.md' } },
  },
} satisfies Meta<Glyph>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {
    char: "◐",
    label: "Twitch",
  },
};

export const Decorative: Story = {
  args: {
    char: "◐",
    label: undefined,
  },
};

export const Small: Story = {
  args: {
    char: "◐",
    label: "Twitch",
    size: 20,
  },
};

export const Large: Story = {
  args: {
    char: "◐",
    label: "Twitch",
    size: 44,
  },
};

/** The component beside the reference declarations its values were taken from. */
export const Anatomy_: Story = {
  name: 'Anatomy & reference',
  render: () => ({ Component: Anatomy, props: { component: 'Glyph' } }),
};
