// GENERATED by scripts/build-stories.mjs from stories/samples.json. Edit that, not this.
import type { Meta, StoryObj } from '@storybook/svelte-vite';
import Icon from '../src/primitives/Icon.svelte';
import Anatomy from './support/Anatomy.svelte';

const meta = {
  title: 'Primitives/Icon',
  component: Icon,
  tags: ['autodocs'],
  parameters: {
    docs: { description: { component: 'Specification: docs/Icon.md' } },
  },
} satisfies Meta<Icon>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {
    name: "gear",
  },
};

export const Labelled: Story = {
  args: {
    name: "bell",
    label: "Értesítések",
  },
};

export const Large: Story = {
  args: {
    name: "calendar",
    size: 44,
    stroke: 1.2,
  },
};

export const HeavyStroke: Story = {
  args: {
    name: "check",
    size: 32,
    stroke: 2,
  },
};

/** The component beside the reference declarations its values were taken from. */
export const Anatomy_: Story = {
  name: 'Anatomy & reference',
  render: () => ({ Component: Anatomy, props: { component: 'Icon' } }),
};
