// GENERATED by scripts/build-stories.mjs from stories/samples.json. Edit that, not this.
import type { Meta, StoryObj } from '@storybook/svelte-vite';
import IconButton from '../src/primitives/IconButton.svelte';
import Anatomy from './support/Anatomy.svelte';

const meta = {
  title: 'Primitives/IconButton',
  component: IconButton,
  tags: ['autodocs'],
  parameters: {
    docs: { description: { component: 'Specification: docs/IconButton.md' } },
  },
} satisfies Meta<IconButton>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Bare: Story = {
  args: {
    icon: "gear",
    label: "Beállítások",
    variant: "bare",
  },
};

export const Circle: Story = {
  args: {
    icon: "gear",
    label: "Beállítások",
    variant: "circle",
    size: 17,
  },
};

export const Disabled: Story = {
  args: {
    icon: "gear",
    label: "Beállítások",
    variant: "circle",
    disabled: true,
  },
};

export const Link: Story = {
  args: {
    icon: "back",
    label: "Vissza",
    variant: "bare",
    href: "#back",
  },
};

/** The component beside the reference declarations its values were taken from. */
export const Anatomy_: Story = {
  name: 'Anatomy & reference',
  render: () => ({ Component: Anatomy, props: { component: 'IconButton' } }),
};
