// GENERATED by scripts/build-stories.mjs from stories/samples.json. Edit that, not this.
import type { Meta, StoryObj } from '@storybook/svelte-vite';
import LabelledInput from '../src/patterns/LabelledInput.svelte';
import Anatomy from './support/Anatomy.svelte';

const meta = {
  title: 'Patterns/LabelledInput',
  component: LabelledInput,
  tags: ['autodocs'],
  parameters: {
    docs: { description: { component: 'Specification: docs/LabelledInput.md' } },
  },
} satisfies Meta<LabelledInput>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {
    label: "Kiszolgáló címe",
    value: "http://192.168.1.10:1421",
  },
};

export const Empty: Story = {
  args: {
    label: "Kiszolgáló címe",
    value: "",
    placeholder: "http://",
  },
};

export const Invalid: Story = {
  args: {
    label: "Kiszolgáló címe",
    value: "192.168",
    error: "Nem érvényes cím",
  },
};

export const Disabled: Story = {
  args: {
    label: "Kiszolgáló címe",
    value: "http://192.168.1.10:1421",
    disabled: true,
  },
};

/** The component beside the reference declarations its values were taken from. */
export const Anatomy_: Story = {
  name: 'Anatomy & reference',
  render: () => ({ Component: Anatomy, props: { component: 'LabelledInput' } }),
};
