// GENERATED by scripts/build-stories.mjs from stories/samples.json. Edit that, not this.
import type { Meta, StoryObj } from '@storybook/svelte-vite';
import List from '../src/primitives/List.svelte';
import Anatomy from './support/Anatomy.svelte';
import { s } from './support/snippet.js';

const meta = {
  title: 'Primitives/List',
  component: List,
  tags: ['autodocs'],
  parameters: {
    docs: { description: { component: 'Specification: docs/List.md' } },
  },
} satisfies Meta<List>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {
    children: s('A lista tartalma'),
  },
};

export const Flush: Story = {
  args: {
    children: s('A lista tartalma'),
    flush: true,
  },
};

export const AsList: Story = {
  args: {
    children: s('<li>A lista tartalma</li>'),
    as: 'ul',
    'aria-label': 'Források',
  },
};

/** The component beside the reference declarations its values were taken from. */
export const Anatomy_: Story = {
  name: 'Anatomy & reference',
  render: () => ({ Component: Anatomy, props: { component: 'List' } }),
};
