// GENERATED by scripts/build-stories.mjs from stories/samples.json. Edit that, not this.
import type { Meta, StoryObj } from '@storybook/svelte-vite';
import LiveRegion from '../src/a11y/LiveRegion.svelte';
import Anatomy from './support/Anatomy.svelte';

const meta = {
  title: 'Accessibility/LiveRegion',
  component: LiveRegion,
  tags: ['autodocs'],
  parameters: {
    docs: { description: { component: 'Specification: docs/LiveRegion.md' } },
  },
} satisfies Meta<LiveRegion>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {

  },
};

/** The component beside the reference declarations its values were taken from. */
export const Anatomy_: Story = {
  name: 'Anatomy & reference',
  render: () => ({ Component: Anatomy, props: { component: 'LiveRegion' } }),
};
