// GENERATED by scripts/build-stories.mjs from stories/samples.json. Edit that, not this.
import type { Meta, StoryObj } from '@storybook/svelte-vite';
import Lockup from '../src/primitives/Lockup.svelte';
import Anatomy from './support/Anatomy.svelte';

const meta = {
  title: 'Primitives/Lockup',
  component: Lockup,
  tags: ['autodocs'],
  parameters: {
    docs: { description: { component: 'Specification: docs/Lockup.md' } },
  },
} satisfies Meta<Lockup>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {
    name: 'Metocast',
  },
};

export const Rail: Story = {
  args: {
    name: 'Metocast',
    markSize: 18,
    fontSize: 19,
    tracking: 0.75,
  },
};

export const Large: Story = {
  args: {
    name: 'Metocast',
    markSize: 32,
    fontSize: 30,
    tracking: 1.5,
  },
};

/** The component beside the reference declarations its values were taken from. */
export const Anatomy_: Story = {
  name: 'Anatomy & reference',
  render: () => ({ Component: Anatomy, props: { component: 'Lockup' } }),
};
