// GENERATED by scripts/build-stories.mjs from stories/samples.json. Edit that, not this.
import type { Meta, StoryObj } from '@storybook/svelte-vite';
import NativeDateInput from '../src/patterns/NativeDateInput.svelte';
import Anatomy from './support/Anatomy.svelte';

const meta = {
  title: 'Patterns/NativeDateInput',
  component: NativeDateInput,
  tags: ['autodocs'],
  parameters: {
    docs: { description: { component: 'Specification: docs/NativeDateInput.md' } },
  },
} satisfies Meta<NativeDateInput>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Date: Story = {
  args: {
    label: '2026. március 14.',
    icon: 'calendar',
    accessibleName: 'Az esemény dátuma',
    value: '2026-03-14',
  },
};

export const Time: Story = {
  args: {
    label: '09:30',
    icon: 'clock',
    accessibleName: 'Kezdés időpontja',
    value: '09:30',
    type: 'time',
  },
};

export const Disabled: Story = {
  args: {
    label: '2026. március 14.',
    icon: 'calendar',
    accessibleName: 'Az esemény dátuma',
    value: '2026-03-14',
    disabled: true,
  },
};

/** The component beside the reference declarations its values were taken from. */
export const Anatomy_: Story = {
  name: 'Anatomy & reference',
  render: () => ({ Component: Anatomy, props: { component: 'NativeDateInput' } }),
};
