// GENERATED by scripts/build-stories.mjs from stories/samples.json. Edit that, not this.
import type { Meta, StoryObj } from '@storybook/svelte-vite';
import NavigationBar from '../src/patterns/NavigationBar.svelte';
import Anatomy from './support/Anatomy.svelte';

const meta = {
  title: 'Patterns/NavigationBar',
  component: NavigationBar,
  tags: ['autodocs'],
  parameters: {
    docs: { description: { component: 'Specification: docs/NavigationBar.md' } },
  },
} satisfies Meta<NavigationBar>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {
    label: 'Fő navigáció',
    active: 'dashboard',
    items: [
      {
        value: 'dashboard',
        label: 'Vezérlő',
        icon: 'home',
      },
      {
        value: 'events',
        label: 'Események',
        icon: 'calendar',
      },
      {
        value: 'slides',
        label: 'Diák',
        icon: 'slides',
      },
      {
        value: 'settings',
        label: 'Beállítások',
        icon: 'gear',
      },
    ],
  },
};

export const SecondItemActive: Story = {
  args: {
    label: 'Fő navigáció',
    active: 'events',
    items: [
      {
        value: 'dashboard',
        label: 'Vezérlő',
        icon: 'home',
      },
      {
        value: 'events',
        label: 'Események',
        icon: 'calendar',
      },
      {
        value: 'slides',
        label: 'Diák',
        icon: 'slides',
      },
      {
        value: 'settings',
        label: 'Beállítások',
        icon: 'gear',
      },
    ],
  },
};

/** The component beside the reference declarations its values were taken from. */
export const Anatomy_: Story = {
  name: 'Anatomy & reference',
  render: () => ({ Component: Anatomy, props: { component: 'NavigationBar' } }),
};
