// GENERATED by scripts/build-stories.mjs from stories/samples.json. Edit that, not this.
import type { Meta, StoryObj } from '@storybook/svelte-vite';
import NotificationBell from '../src/patterns/NotificationBell.svelte';
import Anatomy from './support/Anatomy.svelte';

const meta = {
  title: 'Patterns/NotificationBell',
  component: NotificationBell,
  tags: ['autodocs'],
  parameters: {
    docs: { description: { component: 'Specification: docs/NotificationBell.md' } },
  },
} satisfies Meta<NotificationBell>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Quiet: Story = {
  args: {
    label: 'Értesítések',
    tier: 'off',
  },
};

export const Ok: Story = {
  args: {
    label: 'Értesítések, 1 új',
    tier: 'ok',
  },
};

export const Warning: Story = {
  args: {
    label: 'Értesítések, 2 új',
    tier: 'warn',
  },
};

export const Critical: Story = {
  args: {
    label: 'Értesítések, 3 sürgős',
    tier: 'live',
    unread: 3,
  },
};

/** The component beside the reference declarations its values were taken from. */
export const Anatomy_: Story = {
  name: 'Anatomy & reference',
  render: () => ({ Component: Anatomy, props: { component: 'NotificationBell' } }),
};
