// GENERATED by scripts/build-stories.mjs from stories/samples.json. Edit that, not this.
import type { Meta, StoryObj } from '@storybook/svelte-vite';
import NotificationCentre from '../src/patterns/NotificationCentre.svelte';
import Anatomy from './support/Anatomy.svelte';
import { s } from './support/snippet.js';

const meta = {
  title: 'Patterns/NotificationCentre',
  component: NotificationCentre,
  tags: ['autodocs'],
  parameters: {
    docs: { description: { component: 'Specification: docs/NotificationCentre.md' } },
  },
} satisfies Meta<NotificationCentre>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Empty: Story = {
  args: {
    open: true,
    title: "Minden rendben",
    emptyTitle: "Csend van a vezérlőben.",
    empty: true,
    emptyHint: "A csatlakozók itt szólalnak meg",
  },
};

export const Populated: Story = {
  args: {
    open: true,
    title: "3 elem",
    emptyTitle: "Csend van a vezérlőben.",
    children: s('Az értesítések listája'),
    onclear: () => {},
  },
};

export const Closed: Story = {
  args: {
    open: false,
    title: "3 elem",
    emptyTitle: "Csend van a vezérlőben.",
  },
};

/** The component beside the reference declarations its values were taken from. */
export const Anatomy_: Story = {
  name: 'Anatomy & reference',
  render: () => ({ Component: Anatomy, props: { component: 'NotificationCentre' } }),
};
