// GENERATED by scripts/build-stories.mjs from stories/samples.json. Edit that, not this.
import type { Meta, StoryObj } from '@storybook/svelte-vite';
import OverviewCell from '../src/primitives/OverviewCell.svelte';
import Anatomy from './support/Anatomy.svelte';

const meta = {
  title: 'Primitives/OverviewCell',
  component: OverviewCell,
  tags: ['autodocs'],
  parameters: {
    docs: { description: { component: 'Specification: docs/OverviewCell.md' } },
  },
} satisfies Meta<OverviewCell>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {
    label: 'Nézők',
    value: '128',
  },
};

export const Live: Story = {
  args: {
    label: 'Adás',
    value: '42:18',
    color: 'var(--status-live)',
    state: 'Adásban',
    pulse: true,
  },
};

export const Divided: Story = {
  args: {
    label: 'Feltöltés',
    value: '3',
    divider: true,
  },
};

/** The component beside the reference declarations its values were taken from. */
export const Anatomy_: Story = {
  name: 'Anatomy & reference',
  render: () => ({ Component: Anatomy, props: { component: 'OverviewCell' } }),
};
