// GENERATED by scripts/build-stories.mjs from stories/samples.json. Edit that, not this.
import type { Meta, StoryObj } from '@storybook/svelte-vite';
import PageHeader from '../src/primitives/PageHeader.svelte';
import Anatomy from './support/Anatomy.svelte';

const meta = {
  title: 'Primitives/PageHeader',
  component: PageHeader,
  tags: ['autodocs'],
  parameters: {
    docs: { description: { component: 'Specification: docs/PageHeader.md' } },
  },
} satisfies Meta<PageHeader>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {
    title: 'Vezérlő',
    eyebrow: 'Vasárnap',
  },
};

export const WithBack: Story = {
  args: {
    title: 'Esemény szerkesztése',
    eyebrow: 'Vasárnap',
    back: {
      label: 'Vissza',
      href: '#events',
    },
  },
};

export const LongTitle: Story = {
  args: {
    title: 'Vasárnapi istentisztelet közvetítése',
    eyebrow: '2026. március 14.',
  },
};

export const AsSubheading: Story = {
  args: {
    title: 'Csatlakozók',
    eyebrow: 'Beállítások',
    level: 2,
  },
};

/** The component beside the reference declarations its values were taken from. */
export const Anatomy_: Story = {
  name: 'Anatomy & reference',
  render: () => ({ Component: Anatomy, props: { component: 'PageHeader' } }),
};
