// GENERATED by scripts/build-stories.mjs from stories/samples.json. Edit that, not this.
import type { Meta, StoryObj } from '@storybook/svelte-vite';
import PresenterPanel from '../src/patterns/PresenterPanel.svelte';
import Anatomy from './support/Anatomy.svelte';

const meta = {
  title: 'Patterns/PresenterPanel',
  component: PresenterPanel,
  tags: ['autodocs'],
  parameters: {
    docs: { description: { component: 'Specification: docs/PresenterPanel.md' } },
  },
} satisfies Meta<PresenterPanel>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {
    label: "Prezentáló nézet",
    url: "http://192.168.1.10:1421/presenter",
    copyLabel: "Másolás",
    clientsLabel: "Csatlakozott eszközök",
    clientsSummary: "2 aktív",
    emptyMessage: "Még senki sem csatlakozott.",
    clients: [
      {
        id: "a",
        name: "Karzat iPad",
        address: "192.168.1.77",
        detail: "12 perce",
      },
      {
        id: "b",
        name: "Szószék laptop",
        address: "192.168.1.32",
        detail: "4 perce",
      },
    ],
  },
};

export const Empty: Story = {
  args: {
    label: "Prezentáló nézet",
    url: "http://192.168.1.10:1421/presenter",
    copyLabel: "Másolás",
    clientsLabel: "Csatlakozott eszközök",
    clientsSummary: "0 aktív",
    emptyMessage: "Még senki sem csatlakozott.",
    clients: [],
  },
};

/** The component beside the reference declarations its values were taken from. */
export const Anatomy_: Story = {
  name: 'Anatomy & reference',
  render: () => ({ Component: Anatomy, props: { component: 'PresenterPanel' } }),
};
