// GENERATED by scripts/build-stories.mjs from stories/samples.json. Edit that, not this.
import type { Meta, StoryObj } from '@storybook/svelte-vite';
import ProgressBar from '../src/primitives/ProgressBar.svelte';
import Anatomy from './support/Anatomy.svelte';

const meta = {
  title: 'Primitives/ProgressBar',
  component: ProgressBar,
  tags: ['autodocs'],
  parameters: {
    docs: { description: { component: 'Specification: docs/ProgressBar.md' } },
  },
} satisfies Meta<ProgressBar>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Determinate: Story = {
  args: {
    label: "Feltöltés",
    value: 62,
    valueText: "62%",
  },
};

export const Complete: Story = {
  args: {
    label: "Feltöltés",
    value: 100,
    valueText: "Kész",
  },
};

export const Indeterminate: Story = {
  args: {
    label: "Kapcsolódás",
    value: undefined,
    valueText: undefined,
  },
};

/** The component beside the reference declarations its values were taken from. */
export const Anatomy_: Story = {
  name: 'Anatomy & reference',
  render: () => ({ Component: Anatomy, props: { component: 'ProgressBar' } }),
};
