// GENERATED by scripts/build-stories.mjs from stories/samples.json. Edit that, not this.
import type { Meta, StoryObj } from '@storybook/svelte-vite';
import RadioGroup from '../src/primitives/RadioGroup.svelte';
import Anatomy from './support/Anatomy.svelte';

const meta = {
  title: 'Primitives/RadioGroup',
  component: RadioGroup,
  tags: ['autodocs'],
  parameters: {
    docs: { description: { component: 'Specification: docs/RadioGroup.md' } },
  },
} satisfies Meta<RadioGroup>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {
    label: "Közvetítés minősége",
    value: "high",
    options: [
      {
        value: "high",
        label: "Magas",
        hint: "1080p, 6 Mb/s",
      },
      {
        value: "medium",
        label: "Közepes",
        hint: "720p, 3 Mb/s",
      },
      {
        value: "low",
        label: "Alacsony",
        hint: "480p, 1 Mb/s",
      },
    ],
  },
};

export const HiddenLegend: Story = {
  args: {
    label: "Közvetítés minősége",
    value: "high",
    options: [
      {
        value: "high",
        label: "Magas",
        hint: "1080p, 6 Mb/s",
      },
      {
        value: "medium",
        label: "Közepes",
        hint: "720p, 3 Mb/s",
      },
      {
        value: "low",
        label: "Alacsony",
        hint: "480p, 1 Mb/s",
      },
    ],
    labelHidden: true,
  },
};

export const WithDisabled: Story = {
  args: {
    label: "Közvetítés minősége",
    value: "high",
    options: [
      {
        value: "high",
        label: "Magas",
        hint: "1080p, 6 Mb/s",
      },
      {
        value: "medium",
        label: "Közepes",
      },
      {
        value: "low",
        label: "Alacsony",
        disabled: true,
        hint: "Nem érhető el ezen a kapcsolaton",
      },
    ],
  },
};

/** The component beside the reference declarations its values were taken from. */
export const Anatomy_: Story = {
  name: 'Anatomy & reference',
  render: () => ({ Component: Anatomy, props: { component: 'RadioGroup' } }),
};
