// GENERATED by scripts/build-stories.mjs from stories/samples.json. Edit that, not this.
import type { Meta, StoryObj } from '@storybook/svelte-vite';
import ReferenceInput from '../src/patterns/ReferenceInput.svelte';
import Anatomy from './support/Anatomy.svelte';

const meta = {
  title: 'Patterns/ReferenceInput',
  component: ReferenceInput,
  tags: ['autodocs'],
  parameters: {
    docs: { description: { component: 'Specification: docs/ReferenceInput.md' } },
  },
} satisfies Meta<ReferenceInput>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Empty: Story = {
  args: {
    label: "Igehely",
    rank: "Első",
    value: "",
    errorMessage: "Nézd meg a helyesírást. Próbáld így: Könyv Fejezet:Vers.",
    notFoundLabel: "Nincs találat",
    placeholder: "Jn 3:16",
  },
};

export const Resolved: Story = {
  args: {
    label: "Igehely",
    rank: "Első",
    value: "Jn 3:16",
    errorMessage: "Nézd meg a helyesírást. Próbáld így: Könyv Fejezet:Vers.",
    notFoundLabel: "Nincs találat",
    statusMessage: "1 vers · RÚF",
    result: {
      verses: [
        {
          n: 16,
          text: "Mert úgy szerette Isten a világot, hogy egyszülött Fiát adta.",
        },
      ],
      translation: "RÚF",
    },
  },
};

export const NotFound: Story = {
  args: {
    label: "Igehely",
    rank: "Első",
    value: "Jn 99:1",
    errorMessage: "Nézd meg a helyesírást. Próbáld így: Könyv Fejezet:Vers.",
    notFoundLabel: "Nincs találat",
    result: {
      invalid: true,
    },
  },
};

/** The component beside the reference declarations its values were taken from. */
export const Anatomy_: Story = {
  name: 'Anatomy & reference',
  render: () => ({ Component: Anatomy, props: { component: 'ReferenceInput' } }),
};
