// GENERATED by scripts/build-stories.mjs from stories/samples.json. Edit that, not this.
import type { Meta, StoryObj } from '@storybook/svelte-vite';
import Row from '../src/primitives/Row.svelte';
import Anatomy from './support/Anatomy.svelte';

const meta = {
  title: 'Primitives/Row',
  component: Row,
  tags: ['autodocs'],
  parameters: {
    docs: { description: { component: 'Specification: docs/Row.md' } },
  },
} satisfies Meta<Row>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {
    title: 'Vasárnapi istentisztelet',
    chevron: false,
    meta: 'Minden héten · 09:30',
  },
};

export const WithDetail: Story = {
  args: {
    title: 'Közvetítés célja',
    chevron: false,
    detail: 'YouTube',
  },
};

export const Link: Story = {
  args: {
    title: 'Események',
    chevron: true,
    meta: '12 közelgő',
    href: '#events',
  },
};

export const Button: Story = {
  args: {
    title: 'Kódoló újraindítása',
    chevron: true,
    onclick: () => {},
  },
};

export const Current: Story = {
  args: {
    title: 'Vezérlő',
    chevron: true,
    href: '#dashboard',
    current: 'page',
  },
};

export const Danger: Story = {
  args: {
    title: 'Esemény törlése',
    chevron: true,
    danger: true,
    onclick: () => {},
  },
};

export const Disabled: Story = {
  args: {
    title: 'Adás újraindítása',
    chevron: true,
    onclick: () => {},
    disabled: true,
  },
};

export const LongContent: Story = {
  args: {
    title: 'Vasárnapi istentisztelet közvetítése a gyülekezeti nagyteremből, tolmácsolással',
    chevron: true,
    meta: 'Ez a másodsoros szöveg elég hosszú ahhoz, hogy levágásra kerüljön a sor végén',
    href: '#long',
  },
};

/** The component beside the reference declarations its values were taken from. */
export const Anatomy_: Story = {
  name: 'Anatomy & reference',
  render: () => ({ Component: Anatomy, props: { component: 'Row' } }),
};
