// GENERATED by scripts/build-stories.mjs from stories/samples.json. Edit that, not this.
import type { Meta, StoryObj } from '@storybook/svelte-vite';
import SectionLabel from '../src/primitives/SectionLabel.svelte';
import Anatomy from './support/Anatomy.svelte';
import { s } from './support/snippet.js';

const meta = {
  title: 'Primitives/SectionLabel',
  component: SectionLabel,
  tags: ['autodocs'],
  parameters: {
    docs: { description: { component: 'Specification: docs/SectionLabel.md' } },
  },
} satisfies Meta<SectionLabel>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {
    children: s('Források'),
  },
};

export const WithHint: Story = {
  args: {
    children: s('Források'),
    hint: '3 eszköz',
  },
};

export const AsHeading: Story = {
  args: {
    children: s('Források'),
    headingLevel: 2,
    hint: '3 eszköz',
  },
};

/** The component beside the reference declarations its values were taken from. */
export const Anatomy_: Story = {
  name: 'Anatomy & reference',
  render: () => ({ Component: Anatomy, props: { component: 'SectionLabel' } }),
};
