// GENERATED by scripts/build-stories.mjs from stories/samples.json. Edit that, not this.
import type { Meta, StoryObj } from '@storybook/svelte-vite';
import Segmented from '../src/primitives/Segmented.svelte';
import Anatomy from './support/Anatomy.svelte';

const meta = {
  title: 'Primitives/Segmented',
  component: Segmented,
  tags: ['autodocs'],
  parameters: {
    docs: { description: { component: 'Specification: docs/Segmented.md' } },
  },
} satisfies Meta<Segmented>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {
    label: 'Nézet',
    value: 'week',
    options: [
      {
        value: 'day',
        label: 'Nap',
        glyph: '·',
      },
      {
        value: 'week',
        label: 'Hét',
        glyph: '▤',
      },
      {
        value: 'month',
        label: 'Hónap',
        glyph: '▦',
      },
    ],
  },
};

export const WithHints: Story = {
  args: {
    label: 'Nézet',
    value: 'week',
    options: [
      {
        value: 'day',
        label: 'Nap',
        glyph: '·',
        hint: 'ma',
      },
      {
        value: 'week',
        label: 'Hét',
        glyph: '▤',
        hint: '7 nap',
      },
      {
        value: 'month',
        label: 'Hónap',
        glyph: '▦',
        hint: '30 nap',
      },
    ],
  },
};

export const TwoOptions: Story = {
  args: {
    label: 'Nézet',
    value: 'auto',
    options: [
      {
        value: 'auto',
        label: 'Automatikus',
      },
      {
        value: 'manual',
        label: 'Kézi',
      },
    ],
  },
};

export const WithDisabled: Story = {
  args: {
    label: 'Nézet',
    value: 'week',
    options: [
      {
        value: 'day',
        label: 'Nap',
      },
      {
        value: 'week',
        label: 'Hét',
      },
      {
        value: 'month',
        label: 'Hónap',
        disabled: true,
      },
    ],
  },
};

/** The component beside the reference declarations its values were taken from. */
export const Anatomy_: Story = {
  name: 'Anatomy & reference',
  render: () => ({ Component: Anatomy, props: { component: 'Segmented' } }),
};
