// GENERATED by scripts/build-stories.mjs from stories/samples.json. Edit that, not this.
import type { Meta, StoryObj } from '@storybook/svelte-vite';
import Select from '../src/primitives/Select.svelte';
import Anatomy from './support/Anatomy.svelte';

const meta = {
  title: 'Primitives/Select',
  component: Select,
  tags: ['autodocs'],
  parameters: {
    docs: { description: { component: 'Specification: docs/Select.md' } },
  },
} satisfies Meta<Select>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {
    label: "Jelenet",
    value: "worship",
    options: [
      {
        value: "worship",
        label: "Dicsőítés",
      },
      {
        value: "sermon",
        label: "Igehirdetés",
      },
      {
        value: "prayer",
        label: "Imádság",
      },
      {
        value: "announcements",
        label: "Hirdetések",
      },
      {
        value: "offline",
        label: "Szünet",
        disabled: true,
      },
    ],
  },
};

export const Invalid: Story = {
  args: {
    label: "Jelenet",
    value: "worship",
    options: [
      {
        value: "worship",
        label: "Dicsőítés",
      },
      {
        value: "sermon",
        label: "Igehirdetés",
      },
      {
        value: "prayer",
        label: "Imádság",
      },
      {
        value: "announcements",
        label: "Hirdetések",
      },
      {
        value: "offline",
        label: "Szünet",
        disabled: true,
      },
    ],
    invalid: true,
  },
};

export const Disabled: Story = {
  args: {
    label: "Jelenet",
    value: "worship",
    options: [
      {
        value: "worship",
        label: "Dicsőítés",
      },
      {
        value: "sermon",
        label: "Igehirdetés",
      },
      {
        value: "prayer",
        label: "Imádság",
      },
      {
        value: "announcements",
        label: "Hirdetések",
      },
      {
        value: "offline",
        label: "Szünet",
        disabled: true,
      },
    ],
    disabled: true,
  },
};

/** The component beside the reference declarations its values were taken from. */
export const Anatomy_: Story = {
  name: 'Anatomy & reference',
  render: () => ({ Component: Anatomy, props: { component: 'Select' } }),
};
