// GENERATED by scripts/build-stories.mjs from stories/samples.json. Edit that, not this.
import type { Meta, StoryObj } from '@storybook/svelte-vite';
import Sheet from '../src/patterns/Sheet.svelte';
import Anatomy from './support/Anatomy.svelte';
import { s } from './support/snippet.js';

const meta = {
  title: 'Patterns/Sheet',
  component: Sheet,
  tags: ['autodocs'],
  parameters: {
    docs: { description: { component: 'Specification: docs/Sheet.md' } },
  },
} satisfies Meta<Sheet>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {
    open: true,
    title: "Beállítások",
    eyebrow: "Csatlakozók",
    children: s('A lap tartalma'),
  },
};

export const Square: Story = {
  args: {
    open: true,
    title: "Beállítások",
    eyebrow: "Csatlakozók",
    children: s('A lap tartalma'),
    rounded: false,
  },
};

export const NoGrabber: Story = {
  args: {
    open: true,
    title: "Beállítások",
    eyebrow: "Csatlakozók",
    children: s('A lap tartalma'),
    grabber: false,
  },
};

export const Closed: Story = {
  args: {
    open: false,
    title: "Beállítások",
    eyebrow: "Csatlakozók",
    children: s('A lap tartalma'),
  },
};

/** The component beside the reference declarations its values were taken from. */
export const Anatomy_: Story = {
  name: 'Anatomy & reference',
  render: () => ({ Component: Anatomy, props: { component: 'Sheet' } }),
};
