// GENERATED by scripts/build-stories.mjs from stories/samples.json. Edit that, not this.
import type { Meta, StoryObj } from '@storybook/svelte-vite';
import Skeleton from '../src/primitives/Skeleton.svelte';
import Anatomy from './support/Anatomy.svelte';

const meta = {
  title: 'Primitives/Skeleton',
  component: Skeleton,
  tags: ['autodocs'],
  parameters: {
    docs: { description: { component: 'Specification: docs/Skeleton.md' } },
  },
} satisfies Meta<Skeleton>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Text: Story = {
  args: {
    shape: "text",
  },
};

export const Paragraph: Story = {
  args: {
    shape: "text",
    lines: 3,
  },
};

export const Label: Story = {
  args: {
    shape: "label",
    width: "120px",
  },
};

export const Block: Story = {
  args: {
    shape: "block",
  },
};

/** The component beside the reference declarations its values were taken from. */
export const Anatomy_: Story = {
  name: 'Anatomy & reference',
  render: () => ({ Component: Anatomy, props: { component: 'Skeleton' } }),
};
