// GENERATED by scripts/build-stories.mjs from stories/samples.json. Edit that, not this.
import type { Meta, StoryObj } from '@storybook/svelte-vite';
import SlideQueue from '../src/patterns/SlideQueue.svelte';
import Anatomy from './support/Anatomy.svelte';

const meta = {
  title: 'Patterns/SlideQueue',
  component: SlideQueue,
  tags: ['autodocs'],
  parameters: {
    docs: { description: { component: 'Specification: docs/SlideQueue.md' } },
  },
} satisfies Meta<SlideQueue>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {
    label: "Dia sor",
    summary: "2 / 4 kitöltve",
    openLabel: "Megnyitás",
    clearLabel: "Ürítés",
    emptyLabel: "Üres hely",
    slots: [
      {
        index: 1,
        title: "Köszöntés",
        loaded: true,
      },
      {
        index: 2,
        title: "Jn 3:16",
      },
      {
        index: 3,
      },
      {
        index: 4,
      },
    ],
  },
};

export const AllEmpty: Story = {
  args: {
    label: "Dia sor",
    summary: "0 / 4 kitöltve",
    openLabel: "Megnyitás",
    clearLabel: "Ürítés",
    emptyLabel: "Üres hely",
    slots: [
      {
        index: 1,
      },
      {
        index: 2,
      },
      {
        index: 3,
      },
      {
        index: 4,
      },
    ],
  },
};

/** The component beside the reference declarations its values were taken from. */
export const Anatomy_: Story = {
  name: 'Anatomy & reference',
  render: () => ({ Component: Anatomy, props: { component: 'SlideQueue' } }),
};
