// GENERATED by scripts/build-stories.mjs from stories/samples.json. Edit that, not this.
import type { Meta, StoryObj } from '@storybook/svelte-vite';
import SlideSearch from '../src/patterns/SlideSearch.svelte';
import Anatomy from './support/Anatomy.svelte';

const meta = {
  title: 'Patterns/SlideSearch',
  component: SlideSearch,
  tags: ['autodocs'],
  parameters: {
    docs: { description: { component: 'Specification: docs/SlideSearch.md' } },
  },
} satisfies Meta<SlideSearch>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {
    label: "Dia keresés",
    searchLabel: "Fájl keresése",
    placeholder: "Koppints a legutóbbi diák megjelenítéséhez",
    filter: "",
    openLabel: "Megnyitás",
    queueLabel: "Sorba",
    emptyMessage: "Nincs találat erre a keresésre.",
    results: [
      {
        id: "a",
        group: "Vasárnapi diák",
        title: "Köszöntés",
        position: "01",
      },
      {
        id: "b",
        group: "Vasárnapi diák",
        title: "Jn 3:16",
        position: "12",
      },
      {
        id: "c",
        group: "Ünnepi diák",
        title: "Áldás",
        position: "40",
      },
    ],
  },
};

export const Empty: Story = {
  args: {
    label: "Dia keresés",
    searchLabel: "Fájl keresése",
    placeholder: "Koppints a legutóbbi diák megjelenítéséhez",
    filter: "",
    openLabel: "Megnyitás",
    queueLabel: "Sorba",
    emptyMessage: "Nincs találat erre a keresésre.",
    results: [],
  },
};

export const QueueDisabled: Story = {
  args: {
    label: "Dia keresés",
    searchLabel: "Fájl keresése",
    placeholder: "Koppints a legutóbbi diák megjelenítéséhez",
    filter: "",
    openLabel: "Megnyitás",
    queueLabel: "Sorba",
    emptyMessage: "Nincs találat erre a keresésre.",
    results: [
      {
        id: "a",
        group: "Vasárnapi diák",
        title: "Köszöntés",
        position: "01",
      },
      {
        id: "b",
        group: "Vasárnapi diák",
        title: "Jn 3:16",
        position: "12",
      },
      {
        id: "c",
        group: "Ünnepi diák",
        title: "Áldás",
        position: "40",
      },
    ],
    queueDisabled: true,
  },
};

/** The component beside the reference declarations its values were taken from. */
export const Anatomy_: Story = {
  name: 'Anatomy & reference',
  render: () => ({ Component: Anatomy, props: { component: 'SlideSearch' } }),
};
