// GENERATED by scripts/build-stories.mjs from stories/samples.json. Edit that, not this.
import type { Meta, StoryObj } from '@storybook/svelte-vite';
import Spinner from '../src/primitives/Spinner.svelte';
import Anatomy from './support/Anatomy.svelte';

const meta = {
  title: 'Primitives/Spinner',
  component: Spinner,
  tags: ['autodocs'],
  parameters: {
    docs: { description: { component: 'Specification: docs/Spinner.md' } },
  },
} satisfies Meta<Spinner>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {
    label: "Betöltés",
  },
};

export const Small: Story = {
  args: {
    label: "Betöltés",
    size: 14,
  },
};

export const Large: Story = {
  args: {
    label: "Betöltés",
    size: 44,
  },
};

/** The component beside the reference declarations its values were taken from. */
export const Anatomy_: Story = {
  name: 'Anatomy & reference',
  render: () => ({ Component: Anatomy, props: { component: 'Spinner' } }),
};
