// GENERATED by scripts/build-stories.mjs from stories/samples.json. Edit that, not this.
import type { Meta, StoryObj } from '@storybook/svelte-vite';
import Stat from '../src/primitives/Stat.svelte';
import Anatomy from './support/Anatomy.svelte';

const meta = {
  title: 'Primitives/Stat',
  component: Stat,
  tags: ['autodocs'],
  parameters: {
    docs: { description: { component: 'Specification: docs/Stat.md' } },
  },
} satisfies Meta<Stat>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {
    label: 'Nézők',
    value: '128',
  },
};

export const WithUnit: Story = {
  args: {
    label: 'Bitráta',
    value: '5.8',
    unit: 'Mb/s',
  },
};

export const LongValue: Story = {
  args: {
    label: 'Adásidő',
    value: '1:42:18',
  },
};

/** The component beside the reference declarations its values were taken from. */
export const Anatomy_: Story = {
  name: 'Anatomy & reference',
  render: () => ({ Component: Anatomy, props: { component: 'Stat' } }),
};
