// GENERATED by scripts/build-stories.mjs from stories/samples.json. Edit that, not this.
import type { Meta, StoryObj } from '@storybook/svelte-vite';
import StatusDot from '../src/primitives/StatusDot.svelte';
import Anatomy from './support/Anatomy.svelte';

const meta = {
  title: 'Primitives/StatusDot',
  component: StatusDot,
  tags: ['autodocs'],
  parameters: {
    docs: { description: { component: 'Specification: docs/StatusDot.md' } },
  },
} satisfies Meta<StatusDot>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Live: Story = {
  args: {
    status: 'live',
    label: 'Adásban',
  },
};

export const Ok: Story = {
  args: {
    status: 'ok',
    label: 'Kapcsolódva',
  },
};

export const Warn: Story = {
  args: {
    status: 'warn',
    label: 'Késleltetés',
  },
};

export const Error: Story = {
  args: {
    status: 'error',
    label: 'Megszakadt',
  },
};

export const Off: Story = {
  args: {
    status: 'off',
    label: 'Készenlét',
  },
};

export const LabelHidden: Story = {
  args: {
    status: 'live',
    label: 'Adásban',
    labelHidden: true,
  },
};

/** The component beside the reference declarations its values were taken from. */
export const Anatomy_: Story = {
  name: 'Anatomy & reference',
  render: () => ({ Component: Anatomy, props: { component: 'StatusDot' } }),
};
