// GENERATED by scripts/build-stories.mjs from stories/samples.json. Edit that, not this.
import type { Meta, StoryObj } from '@storybook/svelte-vite';
import StickyActionBar from '../src/patterns/StickyActionBar.svelte';
import Anatomy from './support/Anatomy.svelte';

const meta = {
  title: 'Patterns/StickyActionBar',
  component: StickyActionBar,
  tags: ['autodocs'],
  parameters: {
    docs: { description: { component: 'Specification: docs/StickyActionBar.md' } },
  },
} satisfies Meta<StickyActionBar>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {
    primary: 'Mentés',
    secondary: 'Mégse',
  },
};

export const PrimaryOnly: Story = {
  args: {
    primary: 'Mentés',
    secondary: '',
  },
};

export const PrimaryDisabled: Story = {
  args: {
    primary: 'Mentés',
    secondary: 'Mégse',
    primaryDisabled: true,
  },
};

/** The component beside the reference declarations its values were taken from. */
export const Anatomy_: Story = {
  name: 'Anatomy & reference',
  render: () => ({ Component: Anatomy, props: { component: 'StickyActionBar' } }),
};
