// GENERATED by scripts/build-stories.mjs from stories/samples.json. Edit that, not this.
import type { Meta, StoryObj } from '@storybook/svelte-vite';
import Table from '../src/patterns/Table.svelte';
import Anatomy from './support/Anatomy.svelte';

const meta = {
  title: 'Patterns/Table',
  component: Table,
  tags: ['autodocs'],
  parameters: {
    docs: { description: { component: 'Specification: docs/Table.md' } },
  },
} satisfies Meta<Table>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {
    caption: "Feltöltések",
    columns: [
      {
        key: "name",
        header: "Név",
        cell: (row) => row.name,
      },
      {
        key: "target",
        header: "Cél",
        cell: (row) => row.target,
      },
      {
        key: "size",
        header: "Méret",
        numeric: true,
        cell: (row) => row.size,
      },
    ],
    rows: [
      {
        id: "a",
        name: "2026-03-14 istentisztelet",
        target: "YouTube",
        size: "2.4 GB",
      },
      {
        id: "b",
        name: "2026-03-07 istentisztelet",
        target: "YouTube",
        size: "2.1 GB",
      },
      {
        id: "c",
        name: "2026-02-28 ifjúsági",
        target: "Facebook",
        size: "1.6 GB",
      },
    ],
  },
};

export const VisibleCaption: Story = {
  args: {
    caption: "Feltöltések",
    columns: [
      {
        key: "name",
        header: "Név",
        cell: (row) => row.name,
      },
      {
        key: "target",
        header: "Cél",
        cell: (row) => row.target,
      },
      {
        key: "size",
        header: "Méret",
        numeric: true,
        cell: (row) => row.size,
      },
    ],
    rows: [
      {
        id: "a",
        name: "2026-03-14 istentisztelet",
        target: "YouTube",
        size: "2.4 GB",
      },
      {
        id: "b",
        name: "2026-03-07 istentisztelet",
        target: "YouTube",
        size: "2.1 GB",
      },
      {
        id: "c",
        name: "2026-02-28 ifjúsági",
        target: "Facebook",
        size: "1.6 GB",
      },
    ],
    captionVisible: true,
  },
};

/** The component beside the reference declarations its values were taken from. */
export const Anatomy_: Story = {
  name: 'Anatomy & reference',
  render: () => ({ Component: Anatomy, props: { component: 'Table' } }),
};
