// GENERATED by scripts/build-stories.mjs from stories/samples.json. Edit that, not this.
import type { Meta, StoryObj } from '@storybook/svelte-vite';
import TextIcon from '../src/primitives/TextIcon.svelte';
import Anatomy from './support/Anatomy.svelte';

const meta = {
  title: 'Primitives/TextIcon',
  component: TextIcon,
  tags: ['autodocs'],
  parameters: {
    docs: { description: { component: 'Specification: docs/TextIcon.md' } },
  },
} satisfies Meta<TextIcon>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {
    char: '·',
  },
};

export const Labelled: Story = {
  args: {
    char: '⌁',
    label: 'Broadlink',
  },
};

export const Other: Story = {
  args: {
    char: '▣',
  },
};

/** The component beside the reference declarations its values were taken from. */
export const Anatomy_: Story = {
  name: 'Anatomy & reference',
  render: () => ({ Component: Anatomy, props: { component: 'TextIcon' } }),
};
