// GENERATED by scripts/build-stories.mjs from stories/samples.json. Edit that, not this.
import type { Meta, StoryObj } from '@storybook/svelte-vite';
import TextField from '../src/primitives/TextField.svelte';
import Anatomy from './support/Anatomy.svelte';

const meta = {
  title: 'Primitives/TextField',
  component: TextField,
  tags: ['autodocs'],
  parameters: {
    docs: { description: { component: 'Specification: docs/TextField.md' } },
  },
} satisfies Meta<TextField>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {
    label: 'Kiszolgáló címe',
    value: '192.168.1.10',
  },
};

export const Empty: Story = {
  args: {
    label: 'Kiszolgáló címe',
    value: '',
    placeholder: '192.168.1.10',
  },
};

export const Invalid: Story = {
  args: {
    label: 'Kiszolgáló címe',
    value: '192.168.1.10',
    invalid: true,
  },
};

export const Readonly: Story = {
  args: {
    label: 'Kiszolgáló címe',
    value: '192.168.1.10',
    readonly: true,
  },
};

export const Disabled: Story = {
  args: {
    label: 'Kiszolgáló címe',
    value: '192.168.1.10',
    disabled: true,
  },
};

/** The component beside the reference declarations its values were taken from. */
export const Anatomy_: Story = {
  name: 'Anatomy & reference',
  render: () => ({ Component: Anatomy, props: { component: 'TextField' } }),
};
