// GENERATED by scripts/build-stories.mjs from stories/samples.json. Edit that, not this.
import type { Meta, StoryObj } from '@storybook/svelte-vite';
import TextArea from '../src/primitives/TextArea.svelte';
import Anatomy from './support/Anatomy.svelte';

const meta = {
  title: 'Primitives/TextArea',
  component: TextArea,
  tags: ['autodocs'],
  parameters: {
    docs: { description: { component: 'Specification: docs/TextArea.md' } },
  },
} satisfies Meta<TextArea>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {
    label: 'Megjegyzés',
    value: 'A tolmács a karzaton ül.',
  },
};

export const Empty: Story = {
  args: {
    label: 'Megjegyzés',
    value: '',
    placeholder: 'Írj megjegyzést',
  },
};

export const Invalid: Story = {
  args: {
    label: 'Megjegyzés',
    value: 'A tolmács a karzaton ül.',
    invalid: true,
  },
};

export const Disabled: Story = {
  args: {
    label: 'Megjegyzés',
    value: 'A tolmács a karzaton ül.',
    disabled: true,
  },
};

export const Tall: Story = {
  args: {
    label: 'Megjegyzés',
    value: 'A tolmács a karzaton ül.',
    rows: 8,
  },
};

/** The component beside the reference declarations its values were taken from. */
export const Anatomy_: Story = {
  name: 'Anatomy & reference',
  render: () => ({ Component: Anatomy, props: { component: 'TextArea' } }),
};
