// GENERATED by scripts/build-stories.mjs from stories/samples.json. Edit that, not this.
import type { Meta, StoryObj } from '@storybook/svelte-vite';
import Toast from '../src/patterns/Toast.svelte';
import Anatomy from './support/Anatomy.svelte';

const meta = {
  title: 'Patterns/Toast',
  component: Toast,
  tags: ['autodocs'],
  parameters: {
    docs: { description: { component: 'Specification: docs/Toast.md' } },
  },
} satisfies Meta<Toast>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Ok: Story = {
  args: {
    kind: 'Csatlakozó',
    source: 'YouTube',
    title: 'A közvetítés elindult',
    body: 'A stream 09:31-kor kezdődött, 1080p felbontásban.',
    tone: 'ok',
  },
};

export const Warning: Story = {
  args: {
    kind: 'Csatlakozó',
    source: 'YouTube',
    title: 'Késleltetés nőtt',
    body: 'A stream 09:31-kor kezdődött, 1080p felbontásban.',
    tone: 'warn',
    state: 'instabil',
  },
};

export const Error: Story = {
  args: {
    kind: 'Csatlakozó',
    source: 'YouTube',
    title: 'A kapcsolat megszakadt',
    body: 'A stream 09:31-kor kezdődött, 1080p felbontásban.',
    tone: 'error',
    state: 'újracsatlakozás',
    actions: [
      {
        label: 'Újra',
        primary: true,
        onclick: () => {},
      },
      {
        label: 'Miért?',
        onclick: () => {},
      },
    ],
  },
};

export const Live: Story = {
  args: {
    kind: 'Csatlakozó',
    source: 'YouTube',
    title: 'Adásban',
    body: 'A stream 09:31-kor kezdődött, 1080p felbontásban.',
    tone: 'live',
    state: 'élő',
  },
};

export const Mono: Story = {
  args: {
    kind: 'Csatlakozó',
    source: 'YouTube',
    title: 'A közvetítés elindult',
    body: 'obs-websocket 5.5.4 · rtmp://a.rtmp.youtube.com/live2',
    tone: 'ok',
    mono: true,
  },
};

export const Dismissible: Story = {
  args: {
    kind: 'Csatlakozó',
    source: 'YouTube',
    title: 'A közvetítés elindult',
    body: 'A stream 09:31-kor kezdődött, 1080p felbontásban.',
    tone: 'ok',
    dismissLabel: 'Elvetés',
    ondismiss: () => {},
  },
};

/** The component beside the reference declarations its values were taken from. */
export const Anatomy_: Story = {
  name: 'Anatomy & reference',
  render: () => ({ Component: Anatomy, props: { component: 'Toast' } }),
};
