// GENERATED by scripts/build-stories.mjs from stories/samples.json. Edit that, not this.
import type { Meta, StoryObj } from '@storybook/svelte-vite';
import ToastOverlay from '../src/patterns/ToastOverlay.svelte';
import Anatomy from './support/Anatomy.svelte';
import { s } from './support/snippet.js';

const meta = {
  title: 'Patterns/ToastOverlay',
  component: ToastOverlay,
  tags: ['autodocs'],
  parameters: {
    docs: { description: { component: 'Specification: docs/ToastOverlay.md' } },
  },
} satisfies Meta<ToastOverlay>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Polite: Story = {
  args: {
    label: "Értesítések",
    children: s('A toastok itt jelennek meg'),
    priority: "polite",
  },
};

export const Assertive: Story = {
  args: {
    label: "Értesítések",
    children: s('A toastok itt jelennek meg'),
    priority: "assertive",
  },
};

/** The component beside the reference declarations its values were taken from. */
export const Anatomy_: Story = {
  name: 'Anatomy & reference',
  render: () => ({ Component: Anatomy, props: { component: 'ToastOverlay' } }),
};
