// GENERATED by scripts/build-stories.mjs from stories/samples.json. Edit that, not this.
import type { Meta, StoryObj } from '@storybook/svelte-vite';
import ToggleRow from '../src/patterns/ToggleRow.svelte';
import Anatomy from './support/Anatomy.svelte';

const meta = {
  title: 'Patterns/ToggleRow',
  component: ToggleRow,
  tags: ['autodocs'],
  parameters: {
    docs: { description: { component: 'Specification: docs/ToggleRow.md' } },
  },
} satisfies Meta<ToggleRow>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {
    label: "Automatikus feltöltés",
    sub: "A felvétel az adás végén felkerül a YouTube-ra.",
  },
};

export const On: Story = {
  args: {
    label: "Automatikus feltöltés",
    sub: "A felvétel az adás végén felkerül a YouTube-ra.",
    checked: true,
  },
};

export const LabelOnly: Story = {
  args: {
    label: "Automatikus feltöltés",
    sub: "",
  },
};

export const Disabled: Story = {
  args: {
    label: "Automatikus feltöltés",
    sub: "A felvétel az adás végén felkerül a YouTube-ra.",
    disabled: true,
  },
};

/** The component beside the reference declarations its values were taken from. */
export const Anatomy_: Story = {
  name: 'Anatomy & reference',
  render: () => ({ Component: Anatomy, props: { component: 'ToggleRow' } }),
};
