// GENERATED by scripts/build-stories.mjs from stories/samples.json. Edit that, not this.
import type { Meta, StoryObj } from '@storybook/svelte-vite';
import Toggle from '../src/primitives/Toggle.svelte';
import Anatomy from './support/Anatomy.svelte';

const meta = {
  title: 'Primitives/Toggle',
  component: Toggle,
  tags: ['autodocs'],
  parameters: {
    docs: { description: { component: 'Specification: docs/Toggle.md' } },
  },
} satisfies Meta<Toggle>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Off: Story = {
  args: {
    label: 'Automatikus feltöltés',
    checked: false,
  },
};

export const On: Story = {
  args: {
    label: 'Automatikus feltöltés',
    checked: true,
  },
};

export const Disabled: Story = {
  args: {
    label: 'Automatikus feltöltés',
    checked: false,
    disabled: true,
  },
};

export const DisabledOn: Story = {
  args: {
    label: 'Automatikus feltöltés',
    checked: true,
    disabled: true,
  },
};

/** The component beside the reference declarations its values were taken from. */
export const Anatomy_: Story = {
  name: 'Anatomy & reference',
  render: () => ({ Component: Anatomy, props: { component: 'Toggle' } }),
};
