// GENERATED by scripts/build-stories.mjs from stories/samples.json. Edit that, not this.
import type { Meta, StoryObj } from '@storybook/svelte-vite';
import TransportDock from '../src/patterns/TransportDock.svelte';
import Anatomy from './support/Anatomy.svelte';

const meta = {
  title: 'Patterns/TransportDock',
  component: TransportDock,
  tags: ['autodocs'],
  parameters: {
    docs: { description: { component: 'Specification: docs/TransportDock.md' } },
  },
} satisfies Meta<TransportDock>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {
    label: "Dia vezérlés",
    status: "Vetítés",
    current: "Jn 3:16 — Mert úgy szerette Isten a világot",
    position: "12",
    actions: [
      {
        icon: "first",
        label: "Első",
        onclick: () => {},
      },
      {
        icon: "prev",
        label: "Előző",
        onclick: () => {},
      },
      {
        icon: "play",
        label: "Vetítés",
        variant: "primary",
        onclick: () => {},
      },
      {
        icon: "next",
        label: "Következő",
        onclick: () => {},
      },
      {
        icon: "stop",
        label: "Leállítás",
        variant: "stop",
        onclick: () => {},
      },
    ],
  },
};

export const Standby: Story = {
  args: {
    label: "Dia vezérlés",
    status: "Készenlét",
    current: "Nincs betöltve dia",
    position: "—",
    actions: [
      {
        icon: "first",
        label: "Első",
        onclick: () => {},
      },
      {
        icon: "prev",
        label: "Előző",
        onclick: () => {},
      },
      {
        icon: "play",
        label: "Vetítés",
        variant: "primary",
        onclick: () => {},
      },
      {
        icon: "next",
        label: "Következő",
        onclick: () => {},
      },
      {
        icon: "stop",
        label: "Leállítás",
        variant: "stop",
        onclick: () => {},
      },
    ],
  },
};

export const ThreeControls: Story = {
  args: {
    label: "Dia vezérlés",
    status: "Vetítés",
    current: "Jn 3:16 — Mert úgy szerette Isten a világot",
    position: "12",
    actions: [
      {
        icon: "prev",
        label: "Előző",
        onclick: () => {},
      },
      {
        icon: "play",
        label: "Vetítés",
        variant: "primary",
        onclick: () => {},
      },
      {
        icon: "next",
        label: "Következő",
        onclick: () => {},
      },
    ],
  },
};

/** The component beside the reference declarations its values were taken from. */
export const Anatomy_: Story = {
  name: 'Anatomy & reference',
  render: () => ({ Component: Anatomy, props: { component: 'TransportDock' } }),
};
